/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import {
  useQuery
} from '@tanstack/react-query';

import { customInstance } from '../../mutator';
import type {
  ErrorResponse,
  LeagueHistoryResponse
} from '../model';




/**
 * 특정 유저의 시즌별 최종 티어 기록을 조회합니다.
 * @summary 특정 유저 리그 히스토리 조회
 */
export const getUserLeagueHistory = (
    userId: number,
 signal?: AbortSignal
) => {


      return customInstance<LeagueHistoryResponse>(
      {url: `/api/v1/league-history/${userId}`, method: 'GET', signal
    },
      );
    }




export const getGetUserLeagueHistoryQueryKey = (userId: number,) => {
    return [
    `/api/v1/league-history/${userId}`
    ] as const;
    }


export const getGetUserLeagueHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getUserLeagueHistory>>, TError = ErrorResponse>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserLeagueHistoryQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserLeagueHistory>>> = ({ signal }) => getUserLeagueHistory(userId, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserLeagueHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getUserLeagueHistory>>>
export type GetUserLeagueHistoryQueryError = ErrorResponse


export function useGetUserLeagueHistory<TData = Awaited<ReturnType<typeof getUserLeagueHistory>>, TError = ErrorResponse>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserLeagueHistory>>,
          TError,
          Awaited<ReturnType<typeof getUserLeagueHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserLeagueHistory<TData = Awaited<ReturnType<typeof getUserLeagueHistory>>, TError = ErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserLeagueHistory>>,
          TError,
          Awaited<ReturnType<typeof getUserLeagueHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserLeagueHistory<TData = Awaited<ReturnType<typeof getUserLeagueHistory>>, TError = ErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 유저 리그 히스토리 조회
 */

export function useGetUserLeagueHistory<TData = Awaited<ReturnType<typeof getUserLeagueHistory>>, TError = ErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserLeagueHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserLeagueHistoryQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 현재 로그인한 유저의 시즌별 최종 티어 기록을 조회합니다.
 * @summary 내 리그 히스토리 조회
 */
export const getMyLeagueHistory = (

 signal?: AbortSignal
) => {


      return customInstance<LeagueHistoryResponse>(
      {url: `/api/v1/league-history/me`, method: 'GET', signal
    },
      );
    }




export const getGetMyLeagueHistoryQueryKey = () => {
    return [
    `/api/v1/league-history/me`
    ] as const;
    }


export const getGetMyLeagueHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getMyLeagueHistory>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyLeagueHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyLeagueHistory>>> = ({ signal }) => getMyLeagueHistory(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyLeagueHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getMyLeagueHistory>>>
export type GetMyLeagueHistoryQueryError = ErrorResponse


export function useGetMyLeagueHistory<TData = Awaited<ReturnType<typeof getMyLeagueHistory>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyLeagueHistory>>,
          TError,
          Awaited<ReturnType<typeof getMyLeagueHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyLeagueHistory<TData = Awaited<ReturnType<typeof getMyLeagueHistory>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyLeagueHistory>>,
          TError,
          Awaited<ReturnType<typeof getMyLeagueHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyLeagueHistory<TData = Awaited<ReturnType<typeof getMyLeagueHistory>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 리그 히스토리 조회
 */

export function useGetMyLeagueHistory<TData = Awaited<ReturnType<typeof getMyLeagueHistory>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyLeagueHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyLeagueHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






