/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ReportDetailResponse,
  ReportSummaryResponse
} from '../model';


export const getGetAllReportsResponseMock = (): ReportSummaryResponse[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({reportId: faker.helpers.arrayElement([faker.number.int(), undefined]), reportType: faker.helpers.arrayElement(['TYPO_ERROR','CONTENT_ERROR','ANSWER_ERROR','OTHER_ERROR'] as const), problemId: faker.helpers.arrayElement([faker.number.int(), undefined]), isResolved: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), submittedAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getGetReportResponseMock = (overrideResponse: Partial<Extract<ReportDetailResponse, object>> = {}): ReportDetailResponse => ({reportId: faker.helpers.arrayElement([faker.number.int(), undefined]), reportType: faker.helpers.arrayElement(['TYPO_ERROR','CONTENT_ERROR','ANSWER_ERROR','OTHER_ERROR'] as const), problemId: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.string.alpha({length: {min: 10, max: 20}}), isResolved: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), submittedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getUpdateReportStatusMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/admin/reports/:reportId/status', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetAllReportsMockHandler = (overrideResponse?: ReportSummaryResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReportSummaryResponse[]> | ReportSummaryResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/reports', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllReportsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetReportMockHandler = (overrideResponse?: ReportDetailResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReportDetailResponse> | ReportDetailResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/reports/:reportId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReportResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAdminReportApiMock = () => [
  getUpdateReportStatusMockHandler(),
  getGetAllReportsMockHandler(),
  getGetReportMockHandler()
]
