/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GetAllReportsParams,
  ReportDetailResponse,
  ReportSummaryResponse
} from '../model';

import { customInstance } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type updateReportStatusResponse200 = {
  data: void
  status: 200
}

export type updateReportStatusResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateReportStatusResponseSuccess = (updateReportStatusResponse200) & {
  headers: Headers;
};
export type updateReportStatusResponseError = (updateReportStatusResponse404) & {
  headers: Headers;
};

export type updateReportStatusResponse = (updateReportStatusResponseSuccess | updateReportStatusResponseError)

export const getUpdateReportStatusUrl = (reportId: number,) => {




  return `/api/v1/admin/reports/${reportId}/status`
}

/**
 * 신고의 해결 상태를 토글합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
 * @summary 신고 해결 상태 변경
 */
export const updateReportStatus = async (reportId: number, options?: RequestInit): Promise<updateReportStatusResponse> => {

  return customInstance<updateReportStatusResponse>(getUpdateReportStatusUrl(reportId),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getUpdateReportStatusMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReportStatus>>, TError,{reportId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateReportStatus>>, TError,{reportId: number}, TContext> => {

const mutationKey = ['updateReportStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReportStatus>>, {reportId: number}> = (props) => {
          const {reportId} = props ?? {};

          return  updateReportStatus(reportId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateReportStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateReportStatus>>>

    export type UpdateReportStatusMutationError = ErrorResponse

    /**
 * @summary 신고 해결 상태 변경
 */
export const useUpdateReportStatus = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReportStatus>>, TError,{reportId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReportStatus>>,
        TError,
        {reportId: number},
        TContext
      > => {
      return useMutation(getUpdateReportStatusMutationOptions(options), queryClient);
    }
    export type getAllReportsResponse200 = {
  data: ReportSummaryResponse[]
  status: 200
}

export type getAllReportsResponseSuccess = (getAllReportsResponse200) & {
  headers: Headers;
};
;

export type getAllReportsResponse = (getAllReportsResponseSuccess)

export const getGetAllReportsUrl = (params?: GetAllReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports?${stringifiedParams}` : `/api/v1/admin/reports`
}

/**
 * 페이징된 신고 목록을 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
 * @summary 신고 목록 조회
 */
export const getAllReports = async (params?: GetAllReportsParams, options?: RequestInit): Promise<getAllReportsResponse> => {

  return customInstance<getAllReportsResponse>(getGetAllReportsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllReportsQueryKey = (params?: GetAllReportsParams,) => {
    return [
    `/api/v1/admin/reports`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAllReports>>, TError = unknown>(params?: GetAllReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllReportsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllReports>>> = ({ signal }) => getAllReports(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllReports>>>
export type GetAllReportsQueryError = unknown


export function useGetAllReports<TData = Awaited<ReturnType<typeof getAllReports>>, TError = unknown>(
 params: undefined |  GetAllReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReports>>,
          TError,
          Awaited<ReturnType<typeof getAllReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllReports<TData = Awaited<ReturnType<typeof getAllReports>>, TError = unknown>(
 params?: GetAllReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReports>>,
          TError,
          Awaited<ReturnType<typeof getAllReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllReports<TData = Awaited<ReturnType<typeof getAllReports>>, TError = unknown>(
 params?: GetAllReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 신고 목록 조회
 */

export function useGetAllReports<TData = Awaited<ReturnType<typeof getAllReports>>, TError = unknown>(
 params?: GetAllReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getReportResponse200 = {
  data: ReportDetailResponse
  status: 200
}

export type getReportResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getReportResponseSuccess = (getReportResponse200) & {
  headers: Headers;
};
export type getReportResponseError = (getReportResponse404) & {
  headers: Headers;
};

export type getReportResponse = (getReportResponseSuccess | getReportResponseError)

export const getGetReportUrl = (reportId: number,) => {




  return `/api/v1/admin/reports/${reportId}`
}

/**
 * 특정 신고의 상세 정보를 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
 * @summary 신고 상세 조회
 */
export const getReport = async (reportId: number, options?: RequestInit): Promise<getReportResponse> => {

  return customInstance<getReportResponse>(getGetReportUrl(reportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReportQueryKey = (reportId: number,) => {
    return [
    `/api/v1/admin/reports/${reportId}`
    ] as const;
    }


export const getGetReportQueryOptions = <TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorResponse>(reportId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReportQueryKey(reportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReport>>> = ({ signal }) => getReport(reportId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportQueryResult = NonNullable<Awaited<ReturnType<typeof getReport>>>
export type GetReportQueryError = ErrorResponse


export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorResponse>(
 reportId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorResponse>(
 reportId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReport>>,
          TError,
          Awaited<ReturnType<typeof getReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorResponse>(
 reportId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 신고 상세 조회
 */

export function useGetReport<TData = Awaited<ReturnType<typeof getReport>>, TError = ErrorResponse>(
 reportId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReportQueryOptions(reportId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






