/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  LeagueHomeResponse,
  LeagueResponse
} from '../model';

import { customInstance } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getLeagueResponse200 = {
  data: LeagueResponse
  status: 200
}

export type getLeagueResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getLeagueResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getLeagueResponseSuccess = (getLeagueResponse200) & {
  headers: Headers;
};
export type getLeagueResponseError = (getLeagueResponse404 | getLeagueResponse500) & {
  headers: Headers;
};

export type getLeagueResponse = (getLeagueResponseSuccess | getLeagueResponseError)

export const getGetLeagueUrl = (leagueId: number,) => {




  return `/api/v1/league/${leagueId}`
}

/**
 * 리그 ID로 리그 정보를 조회합니다<br> <strong>리그 단건 조회는 현재 디자인상 사용하지 않아도 됩니다</strong>
 * @summary 리그 단건 조회
 */
export const getLeague = async (leagueId: number, options?: RequestInit): Promise<getLeagueResponse> => {

  return customInstance<getLeagueResponse>(getGetLeagueUrl(leagueId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLeagueQueryKey = (leagueId: number,) => {
    return [
    `/api/v1/league/${leagueId}`
    ] as const;
    }


export const getGetLeagueQueryOptions = <TData = Awaited<ReturnType<typeof getLeague>>, TError = ErrorResponse>(leagueId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeagueQueryKey(leagueId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeague>>> = ({ signal }) => getLeague(leagueId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: leagueId !== null && leagueId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLeagueQueryResult = NonNullable<Awaited<ReturnType<typeof getLeague>>>
export type GetLeagueQueryError = ErrorResponse


export function useGetLeague<TData = Awaited<ReturnType<typeof getLeague>>, TError = ErrorResponse>(
 leagueId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeague>>,
          TError,
          Awaited<ReturnType<typeof getLeague>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeague<TData = Awaited<ReturnType<typeof getLeague>>, TError = ErrorResponse>(
 leagueId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeague>>,
          TError,
          Awaited<ReturnType<typeof getLeague>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeague<TData = Awaited<ReturnType<typeof getLeague>>, TError = ErrorResponse>(
 leagueId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 리그 단건 조회
 */

export function useGetLeague<TData = Awaited<ReturnType<typeof getLeague>>, TError = ErrorResponse>(
 leagueId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeague>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLeagueQueryOptions(leagueId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type enterHomeResponse200 = {
  data: LeagueHomeResponse
  status: 200
}

export type enterHomeResponse404 = {
  data: ErrorResponse
  status: 404
}

export type enterHomeResponse500 = {
  data: ErrorResponse
  status: 500
}

export type enterHomeResponseSuccess = (enterHomeResponse200) & {
  headers: Headers;
};
export type enterHomeResponseError = (enterHomeResponse404 | enterHomeResponse500) & {
  headers: Headers;
};

export type enterHomeResponse = (enterHomeResponseSuccess | enterHomeResponseError)

export const getEnterHomeUrl = () => {




  return `/api/v1/league/home`
}

/**
 * 리그 페이지에 필요한 시즌 정보 및 팝업 데이터를 리턴합니다.<br> 시즌 정보는 필수적으로 포함합니다<br> containsPopup 필드가 true 면, lastSeasonPopup 에 팝업 정보를 포함합니다. <br> containsPopup 필드가 false 면, lastSeasonPopup 은 null 값을 가집니다.
 * @summary 리그 페이지 home 조회
 */
export const enterHome = async ( options?: RequestInit): Promise<enterHomeResponse> => {

  return customInstance<enterHomeResponse>(getEnterHomeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEnterHomeQueryKey = () => {
    return [
    `/api/v1/league/home`
    ] as const;
    }


export const getEnterHomeQueryOptions = <TData = Awaited<ReturnType<typeof enterHome>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnterHomeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof enterHome>>> = ({ signal }) => enterHome({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnterHomeQueryResult = NonNullable<Awaited<ReturnType<typeof enterHome>>>
export type EnterHomeQueryError = ErrorResponse


export function useEnterHome<TData = Awaited<ReturnType<typeof enterHome>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterHome>>,
          TError,
          Awaited<ReturnType<typeof enterHome>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterHome<TData = Awaited<ReturnType<typeof enterHome>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterHome>>,
          TError,
          Awaited<ReturnType<typeof enterHome>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterHome<TData = Awaited<ReturnType<typeof enterHome>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 리그 페이지 home 조회
 */

export function useEnterHome<TData = Awaited<ReturnType<typeof enterHome>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterHome>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnterHomeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






