/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppShellRouteRouteImport } from './routes/_authenticated/_app-shell/route'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedAppShellLeagueRouteImport } from './routes/_authenticated/_app-shell/league'
import { Route as AuthenticatedAppShellMainRouteImport } from './routes/_authenticated/_app-shell/main'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingSuccessRouteImport } from './routes/_authenticated/onboarding/success'
import { Route as AuthenticatedAppShellLearningIndexRouteImport } from './routes/_authenticated/_app-shell/learning.index'
import { Route as AuthenticatedAppShellMyIndexRouteImport } from './routes/_authenticated/_app-shell/my.index'
import { Route as LoginOauth2CodeProviderRouteImport } from './routes/login.oauth2.code.$provider'
import { Route as AuthenticatedAppShellLearningChapterIdUnitIdRouteImport } from './routes/_authenticated/_app-shell/learning.$chapterId.$unitId'
import { Route as AuthenticatedAppShellMyFriendsSearchRouteImport } from './routes/_authenticated/_app-shell/my.friends.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppShellRouteRoute =
  AuthenticatedAppShellRouteRouteImport.update({
    id: '/_app-shell',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppShellLeagueRoute =
  AuthenticatedAppShellLeagueRouteImport.update({
    id: '/league',
    path: '/league',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)
const AuthenticatedAppShellMainRoute =
  AuthenticatedAppShellMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingSuccessRoute =
  AuthenticatedOnboardingSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedAppShellLearningIndexRoute =
  AuthenticatedAppShellLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)
const AuthenticatedAppShellMyIndexRoute =
  AuthenticatedAppShellMyIndexRouteImport.update({
    id: '/my/',
    path: '/my/',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)
const LoginOauth2CodeProviderRoute = LoginOauth2CodeProviderRouteImport.update({
  id: '/login/oauth2/code/$provider',
  path: '/login/oauth2/code/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppShellLearningChapterIdUnitIdRoute =
  AuthenticatedAppShellLearningChapterIdUnitIdRouteImport.update({
    id: '/learning/$chapterId/$unitId',
    path: '/learning/$chapterId/$unitId',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)
const AuthenticatedAppShellMyFriendsSearchRoute =
  AuthenticatedAppShellMyFriendsSearchRouteImport.update({
    id: '/my/friends/search',
    path: '/my/friends/search',
    getParentRoute: () => AuthenticatedAppShellRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/league': typeof AuthenticatedAppShellLeagueRoute
  '/main': typeof AuthenticatedAppShellMainRoute
  '/onboarding/success': typeof AuthenticatedOnboardingSuccessRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/learning/': typeof AuthenticatedAppShellLearningIndexRoute
  '/my/': typeof AuthenticatedAppShellMyIndexRoute
  '/learning/$chapterId/$unitId': typeof AuthenticatedAppShellLearningChapterIdUnitIdRoute
  '/my/friends/search': typeof AuthenticatedAppShellMyFriendsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/terms': typeof TermsRoute
  '/league': typeof AuthenticatedAppShellLeagueRoute
  '/main': typeof AuthenticatedAppShellMainRoute
  '/onboarding/success': typeof AuthenticatedOnboardingSuccessRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/learning': typeof AuthenticatedAppShellLearningIndexRoute
  '/my': typeof AuthenticatedAppShellMyIndexRoute
  '/learning/$chapterId/$unitId': typeof AuthenticatedAppShellLearningChapterIdUnitIdRoute
  '/my/friends/search': typeof AuthenticatedAppShellMyFriendsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/restore': typeof RestoreRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_app-shell': typeof AuthenticatedAppShellRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/_app-shell/league': typeof AuthenticatedAppShellLeagueRoute
  '/_authenticated/_app-shell/main': typeof AuthenticatedAppShellMainRoute
  '/_authenticated/onboarding/success': typeof AuthenticatedOnboardingSuccessRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/_authenticated/_app-shell/learning/': typeof AuthenticatedAppShellLearningIndexRoute
  '/_authenticated/_app-shell/my/': typeof AuthenticatedAppShellMyIndexRoute
  '/_authenticated/_app-shell/learning/$chapterId/$unitId': typeof AuthenticatedAppShellLearningChapterIdUnitIdRoute
  '/_authenticated/_app-shell/my/friends/search': typeof AuthenticatedAppShellMyFriendsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/restore'
    | '/terms'
    | '/onboarding'
    | '/league'
    | '/main'
    | '/onboarding/success'
    | '/onboarding/'
    | '/login/oauth2/code/$provider'
    | '/learning/'
    | '/my/'
    | '/learning/$chapterId/$unitId'
    | '/my/friends/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/restore'
    | '/terms'
    | '/league'
    | '/main'
    | '/onboarding/success'
    | '/onboarding'
    | '/login/oauth2/code/$provider'
    | '/learning'
    | '/my'
    | '/learning/$chapterId/$unitId'
    | '/my/friends/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/restore'
    | '/terms'
    | '/_authenticated/_app-shell'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app-shell/league'
    | '/_authenticated/_app-shell/main'
    | '/_authenticated/onboarding/success'
    | '/_authenticated/onboarding/'
    | '/login/oauth2/code/$provider'
    | '/_authenticated/_app-shell/learning/'
    | '/_authenticated/_app-shell/my/'
    | '/_authenticated/_app-shell/learning/$chapterId/$unitId'
    | '/_authenticated/_app-shell/my/friends/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RestoreRoute: typeof RestoreRoute
  TermsRoute: typeof TermsRoute
  LoginOauth2CodeProviderRoute: typeof LoginOauth2CodeProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app-shell': {
      id: '/_authenticated/_app-shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppShellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app-shell/league': {
      id: '/_authenticated/_app-shell/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AuthenticatedAppShellLeagueRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
    '/_authenticated/_app-shell/main': {
      id: '/_authenticated/_app-shell/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedAppShellMainRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/success': {
      id: '/_authenticated/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof AuthenticatedOnboardingSuccessRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/_app-shell/learning/': {
      id: '/_authenticated/_app-shell/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof AuthenticatedAppShellLearningIndexRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
    '/_authenticated/_app-shell/my/': {
      id: '/_authenticated/_app-shell/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof AuthenticatedAppShellMyIndexRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
    '/login/oauth2/code/$provider': {
      id: '/login/oauth2/code/$provider'
      path: '/login/oauth2/code/$provider'
      fullPath: '/login/oauth2/code/$provider'
      preLoaderRoute: typeof LoginOauth2CodeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app-shell/learning/$chapterId/$unitId': {
      id: '/_authenticated/_app-shell/learning/$chapterId/$unitId'
      path: '/learning/$chapterId/$unitId'
      fullPath: '/learning/$chapterId/$unitId'
      preLoaderRoute: typeof AuthenticatedAppShellLearningChapterIdUnitIdRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
    '/_authenticated/_app-shell/my/friends/search': {
      id: '/_authenticated/_app-shell/my/friends/search'
      path: '/my/friends/search'
      fullPath: '/my/friends/search'
      preLoaderRoute: typeof AuthenticatedAppShellMyFriendsSearchRouteImport
      parentRoute: typeof AuthenticatedAppShellRouteRoute
    }
  }
}

interface AuthenticatedAppShellRouteRouteChildren {
  AuthenticatedAppShellLeagueRoute: typeof AuthenticatedAppShellLeagueRoute
  AuthenticatedAppShellMainRoute: typeof AuthenticatedAppShellMainRoute
  AuthenticatedAppShellLearningIndexRoute: typeof AuthenticatedAppShellLearningIndexRoute
  AuthenticatedAppShellMyIndexRoute: typeof AuthenticatedAppShellMyIndexRoute
  AuthenticatedAppShellLearningChapterIdUnitIdRoute: typeof AuthenticatedAppShellLearningChapterIdUnitIdRoute
  AuthenticatedAppShellMyFriendsSearchRoute: typeof AuthenticatedAppShellMyFriendsSearchRoute
}

const AuthenticatedAppShellRouteRouteChildren: AuthenticatedAppShellRouteRouteChildren =
  {
    AuthenticatedAppShellLeagueRoute: AuthenticatedAppShellLeagueRoute,
    AuthenticatedAppShellMainRoute: AuthenticatedAppShellMainRoute,
    AuthenticatedAppShellLearningIndexRoute:
      AuthenticatedAppShellLearningIndexRoute,
    AuthenticatedAppShellMyIndexRoute: AuthenticatedAppShellMyIndexRoute,
    AuthenticatedAppShellLearningChapterIdUnitIdRoute:
      AuthenticatedAppShellLearningChapterIdUnitIdRoute,
    AuthenticatedAppShellMyFriendsSearchRoute:
      AuthenticatedAppShellMyFriendsSearchRoute,
  }

const AuthenticatedAppShellRouteRouteWithChildren =
  AuthenticatedAppShellRouteRoute._addFileChildren(
    AuthenticatedAppShellRouteRouteChildren,
  )

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingSuccessRoute: typeof AuthenticatedOnboardingSuccessRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingSuccessRoute: AuthenticatedOnboardingSuccessRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppShellRouteRoute: typeof AuthenticatedAppShellRouteRouteWithChildren
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppShellRouteRoute: AuthenticatedAppShellRouteRouteWithChildren,
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RestoreRoute: RestoreRoute,
  TermsRoute: TermsRoute,
  LoginOauth2CodeProviderRoute: LoginOauth2CodeProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
