/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { LearningSubmissionSaveRequest } from '../models';
// @ts-ignore
import type { LessonDetailResponse } from '../models';
// @ts-ignore
import type { LessonSubmissionSaveResponse } from '../models';
/**
 * LessonAPIApi - axios parameter creator
 */
export const LessonAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 목록 조회
         * @param {number} unitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLessonInUnit: async (unitId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'unitId' is not null or undefined
            assertParamExists('getAllLessonInUnit', 'unitId', unitId)
            const localVarPath = `/api/v1/lessons/{unitId}`
                .replace(`{${"unitId"}}`, encodeURIComponent(String(unitId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 결과 저장
         * @param {LearningSubmissionSaveRequest} learningSubmissionSaveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveLessonSubmission: async (learningSubmissionSaveRequest: LearningSubmissionSaveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'learningSubmissionSaveRequest' is not null or undefined
            assertParamExists('saveLessonSubmission', 'learningSubmissionSaveRequest', learningSubmissionSaveRequest)
            const localVarPath = `/api/v1/lessons/results`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(learningSubmissionSaveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LessonAPIApi - functional programming interface
 */
export const LessonAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LessonAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 목록 조회
         * @param {number} unitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllLessonInUnit(unitId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LessonDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllLessonInUnit(unitId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LessonAPIApi.getAllLessonInUnit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 결과 저장
         * @param {LearningSubmissionSaveRequest} learningSubmissionSaveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveLessonSubmission(learningSubmissionSaveRequest: LearningSubmissionSaveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LessonSubmissionSaveResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveLessonSubmission(learningSubmissionSaveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LessonAPIApi.saveLessonSubmission']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LessonAPIApi - factory interface
 */
export const LessonAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LessonAPIApiFp(configuration)
    return {
        /**
         * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 목록 조회
         * @param {number} unitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllLessonInUnit(unitId: number, options?: RawAxiosRequestConfig): AxiosPromise<LessonDetailResponse> {
            return localVarFp.getAllLessonInUnit(unitId, options).then((request) => request(axios, basePath));
        },
        /**
         * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
         * @summary 레슨 결과 저장
         * @param {LearningSubmissionSaveRequest} learningSubmissionSaveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveLessonSubmission(learningSubmissionSaveRequest: LearningSubmissionSaveRequest, options?: RawAxiosRequestConfig): AxiosPromise<LessonSubmissionSaveResponse> {
            return localVarFp.saveLessonSubmission(learningSubmissionSaveRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LessonAPIApi - object-oriented interface
 */
export class LessonAPIApi extends BaseAPI {
    /**
     * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
     * @summary 레슨 목록 조회
     * @param {number} unitId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllLessonInUnit(unitId: number, options?: RawAxiosRequestConfig) {
        return LessonAPIApiFp(this.configuration).getAllLessonInUnit(unitId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
     * @summary 레슨 결과 저장
     * @param {LearningSubmissionSaveRequest} learningSubmissionSaveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public saveLessonSubmission(learningSubmissionSaveRequest: LearningSubmissionSaveRequest, options?: RawAxiosRequestConfig) {
        return LessonAPIApiFp(this.configuration).saveLessonSubmission(learningSubmissionSaveRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

