/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { MyLeagueRankWithProfileResponse } from '../models';
/**
 * MyLeagueProfileAPIApi - axios parameter creator
 */
export const MyLeagueProfileAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyLeagueWithProfile: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/ranking/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MyLeagueProfileAPIApi - functional programming interface
 */
export const MyLeagueProfileAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MyLeagueProfileAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyLeagueWithProfile(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MyLeagueRankWithProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyLeagueWithProfile(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MyLeagueProfileAPIApi.getMyLeagueWithProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MyLeagueProfileAPIApi - factory interface
 */
export const MyLeagueProfileAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MyLeagueProfileAPIApiFp(configuration)
    return {
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyLeagueWithProfile(options?: RawAxiosRequestConfig): AxiosPromise<MyLeagueRankWithProfileResponse> {
            return localVarFp.getMyLeagueWithProfile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MyLeagueProfileAPIApi - object-oriented interface
 */
export class MyLeagueProfileAPIApi extends BaseAPI {
    /**
     * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
     * @summary 내 리그·랭킹 요약 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyLeagueWithProfile(options?: RawAxiosRequestConfig) {
        return MyLeagueProfileAPIApiFp(this.configuration).getMyLeagueWithProfile(options).then((request) => request(this.axios, this.basePath));
    }
}

