/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MissionCompletedEvent } from '../models';
// @ts-ignore
import type { PlanetCompletedEvent } from '../models';
// @ts-ignore
import type { QualifiedSolvedEvent } from '../models';
// @ts-ignore
import type { StreakUpdatedEvent } from '../models';
/**
 * TestEventControllerApi - axios parameter creator
 */
export const TestEventControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {MissionCompletedEvent} missionCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mission: async (missionCompletedEvent: MissionCompletedEvent, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'missionCompletedEvent' is not null or undefined
            assertParamExists('mission', 'missionCompletedEvent', missionCompletedEvent)
            const localVarPath = `/api/v1/test/mission-completed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(missionCompletedEvent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PlanetCompletedEvent} planetCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        planetCompleted: async (planetCompletedEvent: PlanetCompletedEvent, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'planetCompletedEvent' is not null or undefined
            assertParamExists('planetCompleted', 'planetCompletedEvent', planetCompletedEvent)
            const localVarPath = `/api/v1/test/planet-completed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(planetCompletedEvent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QualifiedSolvedEvent} qualifiedSolvedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qualified: async (qualifiedSolvedEvent: QualifiedSolvedEvent, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'qualifiedSolvedEvent' is not null or undefined
            assertParamExists('qualified', 'qualifiedSolvedEvent', qualifiedSolvedEvent)
            const localVarPath = `/api/v1/test/qualified-solved`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(qualifiedSolvedEvent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {StreakUpdatedEvent} streakUpdatedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streak: async (streakUpdatedEvent: StreakUpdatedEvent, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'streakUpdatedEvent' is not null or undefined
            assertParamExists('streak', 'streakUpdatedEvent', streakUpdatedEvent)
            const localVarPath = `/api/v1/test/streak`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(streakUpdatedEvent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestEventControllerApi - functional programming interface
 */
export const TestEventControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestEventControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {MissionCompletedEvent} missionCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mission(missionCompletedEvent: MissionCompletedEvent, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mission(missionCompletedEvent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestEventControllerApi.mission']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PlanetCompletedEvent} planetCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async planetCompleted(planetCompletedEvent: PlanetCompletedEvent, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.planetCompleted(planetCompletedEvent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestEventControllerApi.planetCompleted']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QualifiedSolvedEvent} qualifiedSolvedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async qualified(qualifiedSolvedEvent: QualifiedSolvedEvent, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.qualified(qualifiedSolvedEvent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestEventControllerApi.qualified']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {StreakUpdatedEvent} streakUpdatedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async streak(streakUpdatedEvent: StreakUpdatedEvent, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.streak(streakUpdatedEvent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestEventControllerApi.streak']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestEventControllerApi - factory interface
 */
export const TestEventControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestEventControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {MissionCompletedEvent} missionCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mission(missionCompletedEvent: MissionCompletedEvent, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.mission(missionCompletedEvent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PlanetCompletedEvent} planetCompletedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        planetCompleted(planetCompletedEvent: PlanetCompletedEvent, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.planetCompleted(planetCompletedEvent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QualifiedSolvedEvent} qualifiedSolvedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qualified(qualifiedSolvedEvent: QualifiedSolvedEvent, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.qualified(qualifiedSolvedEvent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {StreakUpdatedEvent} streakUpdatedEvent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streak(streakUpdatedEvent: StreakUpdatedEvent, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.streak(streakUpdatedEvent, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TestEventControllerApi - object-oriented interface
 */
export class TestEventControllerApi extends BaseAPI {
    /**
     * 
     * @param {MissionCompletedEvent} missionCompletedEvent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public mission(missionCompletedEvent: MissionCompletedEvent, options?: RawAxiosRequestConfig) {
        return TestEventControllerApiFp(this.configuration).mission(missionCompletedEvent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PlanetCompletedEvent} planetCompletedEvent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public planetCompleted(planetCompletedEvent: PlanetCompletedEvent, options?: RawAxiosRequestConfig) {
        return TestEventControllerApiFp(this.configuration).planetCompleted(planetCompletedEvent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QualifiedSolvedEvent} qualifiedSolvedEvent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public qualified(qualifiedSolvedEvent: QualifiedSolvedEvent, options?: RawAxiosRequestConfig) {
        return TestEventControllerApiFp(this.configuration).qualified(qualifiedSolvedEvent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {StreakUpdatedEvent} streakUpdatedEvent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public streak(streakUpdatedEvent: StreakUpdatedEvent, options?: RawAxiosRequestConfig) {
        return TestEventControllerApiFp(this.configuration).streak(streakUpdatedEvent, options).then((request) => request(this.axios, this.basePath));
    }
}

