/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { LeagueRankRowDto } from '../models';
// @ts-ignore
import type { MyLeagueRankWithProfileResponse } from '../models';
// @ts-ignore
import type { SliceResponseLeagueRankRowDto } from '../models';
/**
 * UserLeagueAPIApi - axios parameter creator
 */
export const UserLeagueAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 특정 리그의 랭킹을 페이지 단위로 조회합니다.<br> - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다.<br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 티어(리그)별 유저 랭킹 조회 (페이지)
         * @param {number} leagueId 리그 ID
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueRanking: async (leagueId: number, pageNum: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leagueId' is not null or undefined
            assertParamExists('getLeagueRanking', 'leagueId', leagueId)
            // verify required parameter 'pageNum' is not null or undefined
            assertParamExists('getLeagueRanking', 'pageNum', pageNum)
            const localVarPath = `/api/v1/ranking/leagues/{leagueId}/page/{pageNum}`
                .replace(`{${"leagueId"}}`, encodeURIComponent(String(leagueId)))
                .replace(`{${"pageNum"}}`, encodeURIComponent(String(pageNum)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹을 페이지 단위로 조회합니다. - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다. <br> 🔐 <strong>Jwt 필요</strong><br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 내 리그 기준 유저 랭킹 조회 (페이지)
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueRankingByUser: async (pageNum: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageNum' is not null or undefined
            assertParamExists('getLeagueRankingByUser', 'pageNum', pageNum)
            const localVarPath = `/api/v1/ranking/user-leagues/page/{pageNum}`
                .replace(`{${"pageNum"}}`, encodeURIComponent(String(pageNum)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyLeagueWithProfile: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/ranking/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserLeagueAPIApi - functional programming interface
 */
export const UserLeagueAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserLeagueAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 특정 리그의 랭킹을 페이지 단위로 조회합니다.<br> - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다.<br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 티어(리그)별 유저 랭킹 조회 (페이지)
         * @param {number} leagueId 리그 ID
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueRanking(leagueId: number, pageNum: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LeagueRankRowDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLeagueRanking(leagueId, pageNum, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserLeagueAPIApi.getLeagueRanking']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹을 페이지 단위로 조회합니다. - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다. <br> 🔐 <strong>Jwt 필요</strong><br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 내 리그 기준 유저 랭킹 조회 (페이지)
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueRankingByUser(pageNum: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LeagueRankRowDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLeagueRankingByUser(pageNum, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserLeagueAPIApi.getLeagueRankingByUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyLeagueWithProfile(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MyLeagueRankWithProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyLeagueWithProfile(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserLeagueAPIApi.getMyLeagueWithProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserLeagueAPIApi - factory interface
 */
export const UserLeagueAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserLeagueAPIApiFp(configuration)
    return {
        /**
         * 특정 리그의 랭킹을 페이지 단위로 조회합니다.<br> - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다.<br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 티어(리그)별 유저 랭킹 조회 (페이지)
         * @param {number} leagueId 리그 ID
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueRanking(leagueId: number, pageNum: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LeagueRankRowDto>> {
            return localVarFp.getLeagueRanking(leagueId, pageNum, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹을 페이지 단위로 조회합니다. - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다. <br> 🔐 <strong>Jwt 필요</strong><br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
         * @summary 내 리그 기준 유저 랭킹 조회 (페이지)
         * @param {number} pageNum 페이지 번호 (0-based)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueRankingByUser(pageNum: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LeagueRankRowDto>> {
            return localVarFp.getLeagueRankingByUser(pageNum, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 내 리그·랭킹 요약 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyLeagueWithProfile(options?: RawAxiosRequestConfig): AxiosPromise<MyLeagueRankWithProfileResponse> {
            return localVarFp.getMyLeagueWithProfile(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserLeagueAPIApi - object-oriented interface
 */
export class UserLeagueAPIApi extends BaseAPI {
    /**
     * 특정 리그의 랭킹을 페이지 단위로 조회합니다.<br> - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다.<br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
     * @summary 티어(리그)별 유저 랭킹 조회 (페이지)
     * @param {number} leagueId 리그 ID
     * @param {number} pageNum 페이지 번호 (0-based)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLeagueRanking(leagueId: number, pageNum: number, options?: RawAxiosRequestConfig) {
        return UserLeagueAPIApiFp(this.configuration).getLeagueRanking(leagueId, pageNum, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자의 현재 리그를 기준으로 랭킹을 페이지 단위로 조회합니다. - `pageNum`은 0부터 시작하는 페이지 번호(0-based)입니다. <br> 🔐 <strong>Jwt 필요</strong><br> 🔐 <strong>다음 페이지가 존재하면 hasNextPage 가 true, 없으면 false</strong><br> 
     * @summary 내 리그 기준 유저 랭킹 조회 (페이지)
     * @param {number} pageNum 페이지 번호 (0-based)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLeagueRankingByUser(pageNum: number, options?: RawAxiosRequestConfig) {
        return UserLeagueAPIApiFp(this.configuration).getLeagueRankingByUser(pageNum, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자의 현재 리그를 기준으로 랭킹 및 프로필 요약 정보를 반환합니다.<br> 🔐 <strong>Jwt 필요</strong> 
     * @summary 내 리그·랭킹 요약 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyLeagueWithProfile(options?: RawAxiosRequestConfig) {
        return UserLeagueAPIApiFp(this.configuration).getMyLeagueWithProfile(options).then((request) => request(this.axios, this.basePath));
    }
}

