/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
/**
 * UserDeletionAPIApi - axios parameter creator
 */
export const UserDeletionAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 메일로 발급된 **삭제 인증 코드**를 확인하고 계정 삭제를 확정합니다.<br> 코드가 유효하면 즉시 삭제가 진행됩니다.<br> 🔐 <strong>Jwt 불필요</strong> (메일 링크 진입 가정)<br> 
         * @summary 계정 삭제 확정(메일 인증 코드 확인)
         * @param {string} mailAuthCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirm: async (mailAuthCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mailAuthCode' is not null or undefined
            assertParamExists('confirm', 'mailAuthCode', mailAuthCode)
            const localVarPath = `/api/v1/users/deletion/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (mailAuthCode !== undefined) {
                localVarQueryParameter['mailAuthCode'] = mailAuthCode;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인한 사용자에게 **계정 삭제 확인 메일**을 발송합니다.<br> 메일 내 확인 버튼(또는 링크)을 통해 최종 확정 단계로 이동합니다.<br> 🔐 <strong>Jwt 필요</strong><br> ✅ 응답은 <code>202 Accepted</code>로, 요청이 접수되었음을 의미합니다. 
         * @summary 계정 삭제 요청(인증 메일 발송)
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        request: async (dest: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dest' is not null or undefined
            assertParamExists('request', 'dest', dest)
            const localVarPath = `/api/v1/users/deletion/request`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (dest !== undefined) {
                localVarQueryParameter['dest'] = dest;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserDeletionAPIApi - functional programming interface
 */
export const UserDeletionAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserDeletionAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 메일로 발급된 **삭제 인증 코드**를 확인하고 계정 삭제를 확정합니다.<br> 코드가 유효하면 즉시 삭제가 진행됩니다.<br> 🔐 <strong>Jwt 불필요</strong> (메일 링크 진입 가정)<br> 
         * @summary 계정 삭제 확정(메일 인증 코드 확인)
         * @param {string} mailAuthCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirm(mailAuthCode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirm(mailAuthCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserDeletionAPIApi.confirm']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인한 사용자에게 **계정 삭제 확인 메일**을 발송합니다.<br> 메일 내 확인 버튼(또는 링크)을 통해 최종 확정 단계로 이동합니다.<br> 🔐 <strong>Jwt 필요</strong><br> ✅ 응답은 <code>202 Accepted</code>로, 요청이 접수되었음을 의미합니다. 
         * @summary 계정 삭제 요청(인증 메일 발송)
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async request(dest: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.request(dest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserDeletionAPIApi.request']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserDeletionAPIApi - factory interface
 */
export const UserDeletionAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserDeletionAPIApiFp(configuration)
    return {
        /**
         * 메일로 발급된 **삭제 인증 코드**를 확인하고 계정 삭제를 확정합니다.<br> 코드가 유효하면 즉시 삭제가 진행됩니다.<br> 🔐 <strong>Jwt 불필요</strong> (메일 링크 진입 가정)<br> 
         * @summary 계정 삭제 확정(메일 인증 코드 확인)
         * @param {string} mailAuthCode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirm(mailAuthCode: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.confirm(mailAuthCode, options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인한 사용자에게 **계정 삭제 확인 메일**을 발송합니다.<br> 메일 내 확인 버튼(또는 링크)을 통해 최종 확정 단계로 이동합니다.<br> 🔐 <strong>Jwt 필요</strong><br> ✅ 응답은 <code>202 Accepted</code>로, 요청이 접수되었음을 의미합니다. 
         * @summary 계정 삭제 요청(인증 메일 발송)
         * @param {string} dest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        request(dest: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.request(dest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserDeletionAPIApi - object-oriented interface
 */
export class UserDeletionAPIApi extends BaseAPI {
    /**
     * 메일로 발급된 **삭제 인증 코드**를 확인하고 계정 삭제를 확정합니다.<br> 코드가 유효하면 즉시 삭제가 진행됩니다.<br> 🔐 <strong>Jwt 불필요</strong> (메일 링크 진입 가정)<br> 
     * @summary 계정 삭제 확정(메일 인증 코드 확인)
     * @param {string} mailAuthCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public confirm(mailAuthCode: string, options?: RawAxiosRequestConfig) {
        return UserDeletionAPIApiFp(this.configuration).confirm(mailAuthCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인한 사용자에게 **계정 삭제 확인 메일**을 발송합니다.<br> 메일 내 확인 버튼(또는 링크)을 통해 최종 확정 단계로 이동합니다.<br> 🔐 <strong>Jwt 필요</strong><br> ✅ 응답은 <code>202 Accepted</code>로, 요청이 접수되었음을 의미합니다. 
     * @summary 계정 삭제 요청(인증 메일 발송)
     * @param {string} dest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public request(dest: string, options?: RawAxiosRequestConfig) {
        return UserDeletionAPIApiFp(this.configuration).request(dest, options).then((request) => request(this.axios, this.basePath));
    }
}

