/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  NoticeDetailResponse,
  SliceResponse
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 공지의 상세 내용을 조회합니다.
 * @summary 공지 상세 조회
 */
export const getNoticeSummary = (
    noticeId: number,
 signal?: AbortSignal
) => {


      return customInstance<NoticeDetailResponse>(
      {url: `/api/v1/notice/${noticeId}`, method: 'GET', signal
    },
      );
    }




export const getGetNoticeSummaryQueryKey = (noticeId: number,) => {
    return [
    `/api/v1/notice/${noticeId}`
    ] as const;
    }


export const getGetNoticeSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getNoticeSummary>>, TError = ErrorResponse>(noticeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNoticeSummaryQueryKey(noticeId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNoticeSummary>>> = ({ signal }) => getNoticeSummary(noticeId, signal);





   return  { queryKey, queryFn, enabled: noticeId !== null && noticeId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNoticeSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getNoticeSummary>>>
export type GetNoticeSummaryQueryError = ErrorResponse


export function useGetNoticeSummary<TData = Awaited<ReturnType<typeof getNoticeSummary>>, TError = ErrorResponse>(
 noticeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoticeSummary>>,
          TError,
          Awaited<ReturnType<typeof getNoticeSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoticeSummary<TData = Awaited<ReturnType<typeof getNoticeSummary>>, TError = ErrorResponse>(
 noticeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoticeSummary>>,
          TError,
          Awaited<ReturnType<typeof getNoticeSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoticeSummary<TData = Awaited<ReturnType<typeof getNoticeSummary>>, TError = ErrorResponse>(
 noticeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 공지 상세 조회
 */

export function useGetNoticeSummary<TData = Awaited<ReturnType<typeof getNoticeSummary>>, TError = ErrorResponse>(
 noticeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNoticeSummaryQueryOptions(noticeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 최신 공지의 요약 리스트를 페이지 단위(0-based)로 조회합니다.
 * @summary 공지 요약 목록 조회
 */
export const getNoticeSummaries = (
    page: number,
 signal?: AbortSignal
) => {


      return customInstance<SliceResponse>(
      {url: `/api/v1/notice/summaries/${page}`, method: 'GET', signal
    },
      );
    }




export const getGetNoticeSummariesQueryKey = (page: number,) => {
    return [
    `/api/v1/notice/summaries/${page}`
    ] as const;
    }


export const getGetNoticeSummariesQueryOptions = <TData = Awaited<ReturnType<typeof getNoticeSummaries>>, TError = unknown>(page: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNoticeSummariesQueryKey(page);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNoticeSummaries>>> = ({ signal }) => getNoticeSummaries(page, signal);





   return  { queryKey, queryFn, enabled: page !== null && page !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNoticeSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof getNoticeSummaries>>>
export type GetNoticeSummariesQueryError = unknown


export function useGetNoticeSummaries<TData = Awaited<ReturnType<typeof getNoticeSummaries>>, TError = unknown>(
 page: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoticeSummaries>>,
          TError,
          Awaited<ReturnType<typeof getNoticeSummaries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoticeSummaries<TData = Awaited<ReturnType<typeof getNoticeSummaries>>, TError = unknown>(
 page: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoticeSummaries>>,
          TError,
          Awaited<ReturnType<typeof getNoticeSummaries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoticeSummaries<TData = Awaited<ReturnType<typeof getNoticeSummaries>>, TError = unknown>(
 page: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 공지 요약 목록 조회
 */

export function useGetNoticeSummaries<TData = Awaited<ReturnType<typeof getNoticeSummaries>>, TError = unknown>(
 page: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoticeSummaries>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNoticeSummariesQueryOptions(page,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






