/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { FollowerResponse } from './followerResponse.ts';

/**
 * 팔로워 목록 슬라이스 응답
 */
export interface FollowerSliceResponse {
  /** 다음 페이지 존재 여부 */
  hasNextPage?: boolean;
  /** 팔로워 목록 */
  contents?: FollowerResponse[];
}
