/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface ObjectiveOptionUpdateRequest {
  optionId: number;
  /** @minLength 1 */
  content: string;
  /** @minLength 1 */
  explanation: string;
  isAnswer: boolean;
}
