/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */

/**
 * 디바이스 플랫폼 (웹은 푸시 미지원, ANDROID 토큰에만 푸시 발송)
 */
export type RegisterFcmTokenRequestPlatform = typeof RegisterFcmTokenRequestPlatform[keyof typeof RegisterFcmTokenRequestPlatform];


export const RegisterFcmTokenRequestPlatform = {
  ANDROID: 'ANDROID',
  WEB: 'WEB',
} as const;
