/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterFcmTokenRequest {
  /**
     * 클라이언트 디바이스 식별자(설치 단위 고유 ID)
     * @minLength 1
     */
  deviceId: string;
  /**
     * FCM 등록 토큰
     * @minLength 1
     */
  fcmToken: string;
}
