/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import type { StagingAnswerResponse } from './stagingAnswerResponse.ts';
import type { StagingOptionResponse } from './stagingOptionResponse.ts';
import type { StagingProblemResponseProblemType } from './stagingProblemResponseProblemType.ts';

export interface StagingProblemResponse {
  problemId?: number;
  problemType?: StagingProblemResponseProblemType;
  instruction?: string;
  content?: string;
  options?: StagingOptionResponse[];
  answer?: StagingAnswerResponse;
}
