/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as AuthenticatedRouteRouteImport } from './../../pages/_authenticated/route'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as AuthenticatedFixedHeaderLayoutRouteRouteImport } from './../../pages/_authenticated/_fixed-header-layout/route'
import { Route as AuthenticatedBlankLayoutRouteRouteImport } from './../../pages/_authenticated/_blank-layout/route'
import { Route as AuthenticatedFixedHeaderLayoutSuccessRouteImport } from './../../pages/_authenticated/_fixed-header-layout/success'
import { Route as AuthenticatedFixedHeaderLayoutOnboardingRouteImport } from './../../pages/_authenticated/_fixed-header-layout/onboarding'
import { Route as AuthenticatedFixedHeaderLayoutMainRouteImport } from './../../pages/_authenticated/_fixed-header-layout/main'
import { Route as AuthenticatedFixedHeaderLayoutLeagueRouteImport } from './../../pages/_authenticated/_fixed-header-layout/league'
import { Route as AuthenticatedFixedHeaderLayoutAddfriendRouteImport } from './../../pages/_authenticated/_fixed-header-layout/addfriend'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/route'
import { Route as AuthenticatedFixedHeaderLayoutLearnIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/learn/index'
import { Route as LoginOauth2CodeProviderRouteImport } from './../../pages/login/oauth2/code/$provider'
import { Route as AuthenticatedBlankLayoutLessonLessonIdRouteImport } from './../../pages/_authenticated/_blank-layout/lesson/$lessonId'
import { Route as AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/learn/$chapterId/index'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/index'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/privacy'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/edit'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/addfriend'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/index'
import { Route as AuthenticatedFixedHeaderLayoutUserMeDeletePageRouteImport } from './../../pages/_authenticated/_fixed-header-layout/user.me.delete.page'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/index'
import { Route as AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRouteImport } from './../../pages/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/$noticeId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFixedHeaderLayoutRouteRoute =
  AuthenticatedFixedHeaderLayoutRouteRouteImport.update({
    id: '/_fixed-header-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlankLayoutRouteRoute =
  AuthenticatedBlankLayoutRouteRouteImport.update({
    id: '/_blank-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutSuccessRoute =
  AuthenticatedFixedHeaderLayoutSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutOnboardingRoute =
  AuthenticatedFixedHeaderLayoutOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutMainRoute =
  AuthenticatedFixedHeaderLayoutMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutLeagueRoute =
  AuthenticatedFixedHeaderLayoutLeagueRouteImport.update({
    id: '/league',
    path: '/league',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutAddfriendRoute =
  AuthenticatedFixedHeaderLayoutAddfriendRouteImport.update({
    id: '/addfriend',
    path: '/addfriend',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteImport.update({
    id: '/_fixed-sidebar-layout',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutLearnIndexRoute =
  AuthenticatedFixedHeaderLayoutLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const LoginOauth2CodeProviderRoute = LoginOauth2CodeProviderRouteImport.update({
  id: '/login/oauth2/code/$provider',
  path: '/login/oauth2/code/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBlankLayoutLessonLessonIdRoute =
  AuthenticatedBlankLayoutLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedBlankLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute =
  AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRouteImport.update({
    id: '/learn/$chapterId/',
    path: '/learn/$chapterId/',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () =>
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRouteImport.update(
    {
      id: '/user/privacy',
      path: '/user/privacy',
      getParentRoute: () =>
        AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
    } as any,
  )
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRouteImport.update({
    id: '/user/edit',
    path: '/user/edit',
    getParentRoute: () =>
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRouteImport.update(
    {
      id: '/user/addfriend',
      path: '/user/addfriend',
      getParentRoute: () =>
        AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
    } as any,
  )
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRouteImport.update(
    {
      id: '/user/notice/',
      path: '/user/notice/',
      getParentRoute: () =>
        AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
    } as any,
  )
const AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute =
  AuthenticatedFixedHeaderLayoutUserMeDeletePageRouteImport.update({
    id: '/user/me/delete/page',
    path: '/user/me/delete/page',
    getParentRoute: () => AuthenticatedFixedHeaderLayoutRouteRoute,
  } as any)
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRouteImport.update(
    {
      id: '/user/notice/$page/',
      path: '/user/notice/$page/',
      getParentRoute: () =>
        AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
    } as any,
  )
const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRouteImport.update(
    {
      id: '/user/notice/$page/$noticeId/',
      path: '/user/notice/$page/$noticeId/',
      getParentRoute: () =>
        AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addfriend': typeof AuthenticatedFixedHeaderLayoutAddfriendRoute
  '/league': typeof AuthenticatedFixedHeaderLayoutLeagueRoute
  '/main': typeof AuthenticatedFixedHeaderLayoutMainRoute
  '/onboarding': typeof AuthenticatedFixedHeaderLayoutOnboardingRoute
  '/success': typeof AuthenticatedFixedHeaderLayoutSuccessRoute
  '/lesson/$lessonId': typeof AuthenticatedBlankLayoutLessonLessonIdRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/learn': typeof AuthenticatedFixedHeaderLayoutLearnIndexRoute
  '/user/addfriend': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute
  '/user/edit': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute
  '/user/privacy': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute
  '/user': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute
  '/learn/$chapterId': typeof AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute
  '/user/me/delete/page': typeof AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute
  '/user/notice': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute
  '/user/notice/$page': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute
  '/user/notice/$page/$noticeId': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addfriend': typeof AuthenticatedFixedHeaderLayoutAddfriendRoute
  '/league': typeof AuthenticatedFixedHeaderLayoutLeagueRoute
  '/main': typeof AuthenticatedFixedHeaderLayoutMainRoute
  '/onboarding': typeof AuthenticatedFixedHeaderLayoutOnboardingRoute
  '/success': typeof AuthenticatedFixedHeaderLayoutSuccessRoute
  '/lesson/$lessonId': typeof AuthenticatedBlankLayoutLessonLessonIdRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/learn': typeof AuthenticatedFixedHeaderLayoutLearnIndexRoute
  '/user/addfriend': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute
  '/user/edit': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute
  '/user/privacy': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute
  '/user': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute
  '/learn/$chapterId': typeof AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute
  '/user/me/delete/page': typeof AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute
  '/user/notice': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute
  '/user/notice/$page': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute
  '/user/notice/$page/$noticeId': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_blank-layout': typeof AuthenticatedBlankLayoutRouteRouteWithChildren
  '/_authenticated/_fixed-header-layout': typeof AuthenticatedFixedHeaderLayoutRouteRouteWithChildren
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteWithChildren
  '/_authenticated/_fixed-header-layout/addfriend': typeof AuthenticatedFixedHeaderLayoutAddfriendRoute
  '/_authenticated/_fixed-header-layout/league': typeof AuthenticatedFixedHeaderLayoutLeagueRoute
  '/_authenticated/_fixed-header-layout/main': typeof AuthenticatedFixedHeaderLayoutMainRoute
  '/_authenticated/_fixed-header-layout/onboarding': typeof AuthenticatedFixedHeaderLayoutOnboardingRoute
  '/_authenticated/_fixed-header-layout/success': typeof AuthenticatedFixedHeaderLayoutSuccessRoute
  '/_authenticated/_blank-layout/lesson/$lessonId': typeof AuthenticatedBlankLayoutLessonLessonIdRoute
  '/login/oauth2/code/$provider': typeof LoginOauth2CodeProviderRoute
  '/_authenticated/_fixed-header-layout/learn/': typeof AuthenticatedFixedHeaderLayoutLearnIndexRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/addfriend': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/edit': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/privacy': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute
  '/_authenticated/_fixed-header-layout/learn/$chapterId/': typeof AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute
  '/_authenticated/_fixed-header-layout/user/me/delete/page': typeof AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute
  '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/$noticeId/': typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addfriend'
    | '/league'
    | '/main'
    | '/onboarding'
    | '/success'
    | '/lesson/$lessonId'
    | '/login/oauth2/code/$provider'
    | '/learn'
    | '/user/addfriend'
    | '/user/edit'
    | '/user/privacy'
    | '/user'
    | '/learn/$chapterId'
    | '/user/me/delete/page'
    | '/user/notice'
    | '/user/notice/$page'
    | '/user/notice/$page/$noticeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addfriend'
    | '/league'
    | '/main'
    | '/onboarding'
    | '/success'
    | '/lesson/$lessonId'
    | '/login/oauth2/code/$provider'
    | '/learn'
    | '/user/addfriend'
    | '/user/edit'
    | '/user/privacy'
    | '/user'
    | '/learn/$chapterId'
    | '/user/me/delete/page'
    | '/user/notice'
    | '/user/notice/$page'
    | '/user/notice/$page/$noticeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_blank-layout'
    | '/_authenticated/_fixed-header-layout'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout'
    | '/_authenticated/_fixed-header-layout/addfriend'
    | '/_authenticated/_fixed-header-layout/league'
    | '/_authenticated/_fixed-header-layout/main'
    | '/_authenticated/_fixed-header-layout/onboarding'
    | '/_authenticated/_fixed-header-layout/success'
    | '/_authenticated/_blank-layout/lesson/$lessonId'
    | '/login/oauth2/code/$provider'
    | '/_authenticated/_fixed-header-layout/learn/'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/addfriend'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/edit'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/privacy'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/'
    | '/_authenticated/_fixed-header-layout/learn/$chapterId/'
    | '/_authenticated/_fixed-header-layout/user/me/delete/page'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/'
    | '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/$noticeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginOauth2CodeProviderRoute: typeof LoginOauth2CodeProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_fixed-header-layout': {
      id: '/_authenticated/_fixed-header-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_blank-layout': {
      id: '/_authenticated/_blank-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedBlankLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_fixed-header-layout/success': {
      id: '/_authenticated/_fixed-header-layout/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutSuccessRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/onboarding': {
      id: '/_authenticated/_fixed-header-layout/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutOnboardingRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/main': {
      id: '/_authenticated/_fixed-header-layout/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutMainRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/league': {
      id: '/_authenticated/_fixed-header-layout/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutLeagueRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/addfriend': {
      id: '/_authenticated/_fixed-header-layout/addfriend'
      path: '/addfriend'
      fullPath: '/addfriend'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutAddfriendRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/learn/': {
      id: '/_authenticated/_fixed-header-layout/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutLearnIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/login/oauth2/code/$provider': {
      id: '/login/oauth2/code/$provider'
      path: '/login/oauth2/code/$provider'
      fullPath: '/login/oauth2/code/$provider'
      preLoaderRoute: typeof LoginOauth2CodeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_blank-layout/lesson/$lessonId': {
      id: '/_authenticated/_blank-layout/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedBlankLayoutLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedBlankLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/learn/$chapterId/': {
      id: '/_authenticated/_fixed-header-layout/learn/$chapterId/'
      path: '/learn/$chapterId'
      fullPath: '/learn/$chapterId'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/privacy': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/privacy'
      path: '/user/privacy'
      fullPath: '/user/privacy'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/edit': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/edit'
      path: '/user/edit'
      fullPath: '/user/edit'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/addfriend': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/addfriend'
      path: '/user/addfriend'
      fullPath: '/user/addfriend'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/'
      path: '/user/notice'
      fullPath: '/user/notice'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/user/me/delete/page': {
      id: '/_authenticated/_fixed-header-layout/user/me/delete/page'
      path: '/user/me/delete/page'
      fullPath: '/user/me/delete/page'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutUserMeDeletePageRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/'
      path: '/user/notice/$page'
      fullPath: '/user/notice/$page'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
    '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/$noticeId/': {
      id: '/_authenticated/_fixed-header-layout/_fixed-sidebar-layout/user/notice/$page/$noticeId/'
      path: '/user/notice/$page/$noticeId'
      fullPath: '/user/notice/$page/$noticeId'
      preLoaderRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRouteImport
      parentRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute
    }
  }
}

interface AuthenticatedBlankLayoutRouteRouteChildren {
  AuthenticatedBlankLayoutLessonLessonIdRoute: typeof AuthenticatedBlankLayoutLessonLessonIdRoute
}

const AuthenticatedBlankLayoutRouteRouteChildren: AuthenticatedBlankLayoutRouteRouteChildren =
  {
    AuthenticatedBlankLayoutLessonLessonIdRoute:
      AuthenticatedBlankLayoutLessonLessonIdRoute,
  }

const AuthenticatedBlankLayoutRouteRouteWithChildren =
  AuthenticatedBlankLayoutRouteRoute._addFileChildren(
    AuthenticatedBlankLayoutRouteRouteChildren,
  )

interface AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteChildren {
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute
}

const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteChildren: AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteChildren =
  {
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserAddfriendRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserEditRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserPrivacyRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserIndexRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticeIndexRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageIndexRoute,
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutUserNoticePageNoticeIdIndexRoute,
  }

const AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteWithChildren =
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute._addFileChildren(
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteChildren,
  )

interface AuthenticatedFixedHeaderLayoutRouteRouteChildren {
  AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute: typeof AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteWithChildren
  AuthenticatedFixedHeaderLayoutAddfriendRoute: typeof AuthenticatedFixedHeaderLayoutAddfriendRoute
  AuthenticatedFixedHeaderLayoutLeagueRoute: typeof AuthenticatedFixedHeaderLayoutLeagueRoute
  AuthenticatedFixedHeaderLayoutMainRoute: typeof AuthenticatedFixedHeaderLayoutMainRoute
  AuthenticatedFixedHeaderLayoutOnboardingRoute: typeof AuthenticatedFixedHeaderLayoutOnboardingRoute
  AuthenticatedFixedHeaderLayoutSuccessRoute: typeof AuthenticatedFixedHeaderLayoutSuccessRoute
  AuthenticatedFixedHeaderLayoutLearnIndexRoute: typeof AuthenticatedFixedHeaderLayoutLearnIndexRoute
  AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute: typeof AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute
  AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute: typeof AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute
}

const AuthenticatedFixedHeaderLayoutRouteRouteChildren: AuthenticatedFixedHeaderLayoutRouteRouteChildren =
  {
    AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRoute:
      AuthenticatedFixedHeaderLayoutFixedSidebarLayoutRouteRouteWithChildren,
    AuthenticatedFixedHeaderLayoutAddfriendRoute:
      AuthenticatedFixedHeaderLayoutAddfriendRoute,
    AuthenticatedFixedHeaderLayoutLeagueRoute:
      AuthenticatedFixedHeaderLayoutLeagueRoute,
    AuthenticatedFixedHeaderLayoutMainRoute:
      AuthenticatedFixedHeaderLayoutMainRoute,
    AuthenticatedFixedHeaderLayoutOnboardingRoute:
      AuthenticatedFixedHeaderLayoutOnboardingRoute,
    AuthenticatedFixedHeaderLayoutSuccessRoute:
      AuthenticatedFixedHeaderLayoutSuccessRoute,
    AuthenticatedFixedHeaderLayoutLearnIndexRoute:
      AuthenticatedFixedHeaderLayoutLearnIndexRoute,
    AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute:
      AuthenticatedFixedHeaderLayoutLearnChapterIdIndexRoute,
    AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute:
      AuthenticatedFixedHeaderLayoutUserMeDeletePageRoute,
  }

const AuthenticatedFixedHeaderLayoutRouteRouteWithChildren =
  AuthenticatedFixedHeaderLayoutRouteRoute._addFileChildren(
    AuthenticatedFixedHeaderLayoutRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlankLayoutRouteRoute: typeof AuthenticatedBlankLayoutRouteRouteWithChildren
  AuthenticatedFixedHeaderLayoutRouteRoute: typeof AuthenticatedFixedHeaderLayoutRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlankLayoutRouteRoute:
    AuthenticatedBlankLayoutRouteRouteWithChildren,
  AuthenticatedFixedHeaderLayoutRouteRoute:
    AuthenticatedFixedHeaderLayoutRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginOauth2CodeProviderRoute: LoginOauth2CodeProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
