/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateUserParams,
  GenerateCustomTokenParams,
  LoginParams,
  LoginResponse
} from '../model';

import { customInstance } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type loginResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = (params: LoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/test/users/login?${stringifiedParams}` : `/api/v1/test/users/login`
}

export const login = async (params: LoginParams, options?: RequestInit): Promise<loginResponse> => {

  return customInstance<loginResponse>(getLoginUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{params: LoginParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{params: LoginParams}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {params: LoginParams}> = (props) => {
          const {params} = props ?? {};

          return  login(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>

    export type LoginMutationError = unknown

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{params: LoginParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {params: LoginParams},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    export type createUserResponse200 = {
  data: LoginResponse
  status: 200
}

export type createUserResponseSuccess = (createUserResponse200) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = (params: CreateUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/test/users/create?${stringifiedParams}` : `/api/v1/test/users/create`
}

export const createUser = async (params: CreateUserParams, options?: RequestInit): Promise<createUserResponse> => {

  return customInstance<createUserResponse>(getCreateUserUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{params: CreateUserParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{params: CreateUserParams}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {params: CreateUserParams}> = (props) => {
          const {params} = props ?? {};

          return  createUser(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>

    export type CreateUserMutationError = unknown

    export const useCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{params: CreateUserParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {params: CreateUserParams},
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options), queryClient);
    }
    export type generateCustomTokenResponse200 = {
  data: LoginResponse
  status: 200
}

export type generateCustomTokenResponseSuccess = (generateCustomTokenResponse200) & {
  headers: Headers;
};
;

export type generateCustomTokenResponse = (generateCustomTokenResponseSuccess)

export const getGenerateCustomTokenUrl = (params: GenerateCustomTokenParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/test/tokens/custom?${stringifiedParams}` : `/api/v1/test/tokens/custom`
}

export const generateCustomToken = async (params: GenerateCustomTokenParams, options?: RequestInit): Promise<generateCustomTokenResponse> => {

  return customInstance<generateCustomTokenResponse>(getGenerateCustomTokenUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getGenerateCustomTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateCustomToken>>, TError,{params: GenerateCustomTokenParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateCustomToken>>, TError,{params: GenerateCustomTokenParams}, TContext> => {

const mutationKey = ['generateCustomToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateCustomToken>>, {params: GenerateCustomTokenParams}> = (props) => {
          const {params} = props ?? {};

          return  generateCustomToken(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateCustomTokenMutationResult = NonNullable<Awaited<ReturnType<typeof generateCustomToken>>>

    export type GenerateCustomTokenMutationError = unknown

    export const useGenerateCustomToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateCustomToken>>, TError,{params: GenerateCustomTokenParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateCustomToken>>,
        TError,
        {params: GenerateCustomTokenParams},
        TContext
      > => {
      return useMutation(getGenerateCustomTokenMutationOptions(options), queryClient);
    }
