/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  LessonDetailResponse,
  LessonSubmissionSaveResponse
} from '../model';


export const getSaveLessonSubmissionResponseMock = (overrideResponse: Partial<Extract<LessonSubmissionSaveResponse, object>> = {}): LessonSubmissionSaveResponse => ({leagueName: faker.string.alpha({length: {min: 10, max: 20}}), userLevelResponse: {currentLevel: faker.helpers.arrayElement([faker.number.int(), undefined]), nextLevel: faker.helpers.arrayElement([faker.number.int(), undefined]), xp: faker.helpers.arrayElement([faker.number.int(), undefined])}, unitSummaryResponse: {unitId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getGetAllLessonInUnitResponseMock = (overrideResponse: Partial<Extract<LessonDetailResponse, object>> = {}): LessonDetailResponse => ({unitSummaryResponse: {unitId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}})}, bookmarkAccessible: faker.datatype.boolean(), wrongAnsweredNoteAccessible: faker.datatype.boolean(), unitId: faker.helpers.arrayElement([faker.number.int(), undefined]), lessonSummaries: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({lessonId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), totalProblem: faker.helpers.arrayElement([faker.number.int(), undefined]), isSolved: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})), ...overrideResponse})


export const getSaveLessonSubmissionMockHandler = (overrideResponse?: LessonSubmissionSaveResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LessonSubmissionSaveResponse> | LessonSubmissionSaveResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/lessons/results', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSaveLessonSubmissionResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAllLessonInUnitMockHandler = (overrideResponse?: LessonDetailResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LessonDetailResponse> | LessonDetailResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/lessons/:unitId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllLessonInUnitResponseMock(),
      { status: 200
      })
  }, options)
}
export const getLessonApiMock = () => [
  getSaveLessonSubmissionMockHandler(),
  getGetAllLessonInUnitMockHandler()
]
