/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  LearningSubmissionSaveRequest,
  LessonDetailResponse,
  LessonSubmissionSaveResponse
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 레슨 결과 저장
 */
export const saveLessonSubmission = (
    learningSubmissionSaveRequest: LearningSubmissionSaveRequest,
 signal?: AbortSignal
) => {


      return customInstance<LessonSubmissionSaveResponse>(
      {url: `/api/v1/lessons/results`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: learningSubmissionSaveRequest, signal
    },
      );
    }



export const getSaveLessonSubmissionMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext> => {

const mutationKey = ['saveLessonSubmission'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveLessonSubmission>>, {data: LearningSubmissionSaveRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveLessonSubmission(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveLessonSubmissionMutationResult = NonNullable<Awaited<ReturnType<typeof saveLessonSubmission>>>
    export type SaveLessonSubmissionMutationBody = LearningSubmissionSaveRequest
    export type SaveLessonSubmissionMutationError = ErrorResponse

    /**
 * @summary 레슨 결과 저장
 */
export const useSaveLessonSubmission = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveLessonSubmission>>,
        TError,
        {data: LearningSubmissionSaveRequest},
        TContext
      > => {
      return useMutation(getSaveLessonSubmissionMutationOptions(options), queryClient);
    }
    /**
 * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 레슨 목록 조회
 */
export const getAllLessonInUnit = (
    unitId: number,
 signal?: AbortSignal
) => {


      return customInstance<LessonDetailResponse>(
      {url: `/api/v1/lessons/${unitId}`, method: 'GET', signal
    },
      );
    }




export const getGetAllLessonInUnitQueryKey = (unitId: number,) => {
    return [
    `/api/v1/lessons/${unitId}`
    ] as const;
    }


export const getGetAllLessonInUnitQueryOptions = <TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLessonInUnitQueryKey(unitId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLessonInUnit>>> = ({ signal }) => getAllLessonInUnit(unitId, signal);





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllLessonInUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLessonInUnit>>>
export type GetAllLessonInUnitQueryError = ErrorResponse


export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLessonInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllLessonInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLessonInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllLessonInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 레슨 목록 조회
 */

export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllLessonInUnitQueryOptions(unitId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






