/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  LearningSubmissionSaveRequest,
  LessonDetailResponse,
  LessonSubmissionSaveResponse
} from '../model';

import { customInstance } from '../../mutator';




export type saveLessonSubmissionResponse200 = {
  data: LessonSubmissionSaveResponse
  status: 200
}

export type saveLessonSubmissionResponse404 = {
  data: ErrorResponse
  status: 404
}

export type saveLessonSubmissionResponseSuccess = (saveLessonSubmissionResponse200) & {
  headers: Headers;
};
export type saveLessonSubmissionResponseError = (saveLessonSubmissionResponse404) & {
  headers: Headers;
};

export type saveLessonSubmissionResponse = (saveLessonSubmissionResponseSuccess | saveLessonSubmissionResponseError)

export const getSaveLessonSubmissionUrl = () => {




  return `/api/v1/lessons/results`
}

/**
 * 레슨 완료 후 문제 풀이 결과를 저장하고 사용자 레벨을 업데이트합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 레슨 결과 저장
 */
export const saveLessonSubmission = async (learningSubmissionSaveRequest: LearningSubmissionSaveRequest, options?: RequestInit): Promise<saveLessonSubmissionResponse> => {

  return customInstance<saveLessonSubmissionResponse>(getSaveLessonSubmissionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(learningSubmissionSaveRequest)
  }
);}




export const getSaveLessonSubmissionMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext> => {

const mutationKey = ['saveLessonSubmission'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveLessonSubmission>>, {data: LearningSubmissionSaveRequest}> = (props) => {
          const {data} = props ?? {};

          return  saveLessonSubmission(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveLessonSubmissionMutationResult = NonNullable<Awaited<ReturnType<typeof saveLessonSubmission>>>
    export type SaveLessonSubmissionMutationBody = LearningSubmissionSaveRequest
    export type SaveLessonSubmissionMutationError = ErrorResponse

    /**
 * @summary 레슨 결과 저장
 */
export const useSaveLessonSubmission = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveLessonSubmission>>, TError,{data: LearningSubmissionSaveRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveLessonSubmission>>,
        TError,
        {data: LearningSubmissionSaveRequest},
        TContext
      > => {
      return useMutation(getSaveLessonSubmissionMutationOptions(options), queryClient);
    }
    export type getAllLessonInUnitResponse200 = {
  data: LessonDetailResponse
  status: 200
}

export type getAllLessonInUnitResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAllLessonInUnitResponseSuccess = (getAllLessonInUnitResponse200) & {
  headers: Headers;
};
export type getAllLessonInUnitResponseError = (getAllLessonInUnitResponse404) & {
  headers: Headers;
};

export type getAllLessonInUnitResponse = (getAllLessonInUnitResponseSuccess | getAllLessonInUnitResponseError)

export const getGetAllLessonInUnitUrl = (unitId: number,) => {




  return `/api/v1/lessons/${unitId}`
}

/**
 * 특정 유닛의 레슨 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 레슨 목록 조회
 */
export const getAllLessonInUnit = async (unitId: number, options?: RequestInit): Promise<getAllLessonInUnitResponse> => {

  return customInstance<getAllLessonInUnitResponse>(getGetAllLessonInUnitUrl(unitId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllLessonInUnitQueryKey = (unitId: number,) => {
    return [
    `/api/v1/lessons/${unitId}`
    ] as const;
    }


export const getGetAllLessonInUnitQueryOptions = <TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllLessonInUnitQueryKey(unitId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllLessonInUnit>>> = ({ signal }) => getAllLessonInUnit(unitId, { signal });





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllLessonInUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getAllLessonInUnit>>>
export type GetAllLessonInUnitQueryError = ErrorResponse


export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLessonInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllLessonInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllLessonInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllLessonInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 레슨 목록 조회
 */

export function useGetAllLessonInUnit<TData = Awaited<ReturnType<typeof getAllLessonInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllLessonInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllLessonInUnitQueryOptions(unitId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






