/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import {
  useMutation
} from '@tanstack/react-query';

import { customInstance } from '../../mutator';
import type {
  ConfirmParams,
  ErrorResponse,
  RequestParams
} from '../model';




/**
 * 로그인한 사용자에게 **계정 삭제 확인 메일**을 발송합니다.<br>
메일 내 확인 버튼(또는 링크)을 통해 최종 확정 단계로 이동합니다.<br>
🔐 <strong>Jwt 필요</strong><br>
✅ 응답은 <code>202 Accepted</code>로, 요청이 접수되었음을 의미합니다.

 * @summary 계정 삭제 요청(인증 메일 발송)
 */
export const request = (
    params: RequestParams,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/users/deletion/request`, method: 'POST',
        params, signal
    },
      );
    }



export const getRequestMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof request>>, TError,{params: RequestParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof request>>, TError,{params: RequestParams}, TContext> => {

const mutationKey = ['request'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof request>>, {params: RequestParams}> = (props) => {
          const {params} = props ?? {};

          return  request(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RequestMutationResult = NonNullable<Awaited<ReturnType<typeof request>>>

    export type RequestMutationError = ErrorResponse

    /**
 * @summary 계정 삭제 요청(인증 메일 발송)
 */
export const useRequest = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof request>>, TError,{params: RequestParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof request>>,
        TError,
        {params: RequestParams},
        TContext
      > => {
      return useMutation(getRequestMutationOptions(options), queryClient);
    }
    /**
 * 메일로 발급된 **삭제 인증 코드**를 확인하고 계정 삭제를 확정합니다.<br>
코드가 유효하면 즉시 삭제가 진행됩니다.<br>
🔐 <strong>Jwt 불필요</strong> (메일 링크 진입 가정)<br>

 * @summary 계정 삭제 확정(메일 인증 코드 확인)
 */
export const confirm = (
    params: ConfirmParams,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/users/deletion/confirm`, method: 'POST',
        params, signal
    },
      );
    }



export const getConfirmMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{params: ConfirmParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{params: ConfirmParams}, TContext> => {

const mutationKey = ['confirm'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirm>>, {params: ConfirmParams}> = (props) => {
          const {params} = props ?? {};

          return  confirm(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof confirm>>>

    export type ConfirmMutationError = ErrorResponse

    /**
 * @summary 계정 삭제 확정(메일 인증 코드 확인)
 */
export const useConfirm = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{params: ConfirmParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirm>>,
        TError,
        {params: ConfirmParams},
        TContext
      > => {
      return useMutation(getConfirmMutationOptions(options), queryClient);
    }
