/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetProblemsParams,
  LessonDetailResponse,
  LessonUpdateRequest,
  PageResponseProblemListItemResponse
} from '../model';

import { customInstance } from '../../mutator';




/**
 * @summary 레슨 상세 (problemCount 포함)
 */
export const getLesson = (
    lessonId: number,
 signal?: AbortSignal
) => {


      return customInstance<LessonDetailResponse>(
      {url: `/api/v1/admin/lessons/${lessonId}`, method: 'GET', signal
    },
      );
    }




export const getGetLessonQueryKey = (lessonId: number,) => {
    return [
    `/api/v1/admin/lessons/${lessonId}`
    ] as const;
    }


export const getGetLessonQueryOptions = <TData = Awaited<ReturnType<typeof getLesson>>, TError = LessonDetailResponse>(lessonId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLessonQueryKey(lessonId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLesson>>> = ({ signal }) => getLesson(lessonId, signal);





   return  { queryKey, queryFn, enabled: lessonId !== null && lessonId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLessonQueryResult = NonNullable<Awaited<ReturnType<typeof getLesson>>>
export type GetLessonQueryError = LessonDetailResponse


export function useGetLesson<TData = Awaited<ReturnType<typeof getLesson>>, TError = LessonDetailResponse>(
 lessonId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLesson>>,
          TError,
          Awaited<ReturnType<typeof getLesson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLesson<TData = Awaited<ReturnType<typeof getLesson>>, TError = LessonDetailResponse>(
 lessonId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLesson>>,
          TError,
          Awaited<ReturnType<typeof getLesson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLesson<TData = Awaited<ReturnType<typeof getLesson>>, TError = LessonDetailResponse>(
 lessonId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 레슨 상세 (problemCount 포함)
 */

export function useGetLesson<TData = Awaited<ReturnType<typeof getLesson>>, TError = LessonDetailResponse>(
 lessonId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLesson>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLessonQueryOptions(lessonId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 레슨 부분 수정 (title 만)
 */
export const updateLesson1 = (
    lessonId: number,
    lessonUpdateRequest: LessonUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/lessons/${lessonId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: lessonUpdateRequest, signal
    },
      );
    }



export const getUpdateLesson1MutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson1>>, TError,{lessonId: number;data: LessonUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLesson1>>, TError,{lessonId: number;data: LessonUpdateRequest}, TContext> => {

const mutationKey = ['updateLesson1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLesson1>>, {lessonId: number;data: LessonUpdateRequest}> = (props) => {
          const {lessonId,data} = props ?? {};

          return  updateLesson1(lessonId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLesson1MutationResult = NonNullable<Awaited<ReturnType<typeof updateLesson1>>>
    export type UpdateLesson1MutationBody = LessonUpdateRequest
    export type UpdateLesson1MutationError = void

    /**
 * @summary 레슨 부분 수정 (title 만)
 */
export const useUpdateLesson1 = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson1>>, TError,{lessonId: number;data: LessonUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLesson1>>,
        TError,
        {lessonId: number;data: LessonUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateLesson1MutationOptions(options), queryClient);
    }
    /**
 * @summary 레슨의 문제 목록
 */
export const getProblems = (
    lessonId: number,
    params?: GetProblemsParams,
 signal?: AbortSignal
) => {


      return customInstance<PageResponseProblemListItemResponse>(
      {url: `/api/v1/admin/lessons/${lessonId}/problems`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetProblemsQueryKey = (lessonId: number,
    params?: GetProblemsParams,) => {
    return [
    `/api/v1/admin/lessons/${lessonId}/problems`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProblemsQueryOptions = <TData = Awaited<ReturnType<typeof getProblems>>, TError = unknown>(lessonId: number,
    params?: GetProblemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProblemsQueryKey(lessonId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProblems>>> = ({ signal }) => getProblems(lessonId,params, signal);





   return  { queryKey, queryFn, enabled: lessonId !== null && lessonId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProblemsQueryResult = NonNullable<Awaited<ReturnType<typeof getProblems>>>
export type GetProblemsQueryError = unknown


export function useGetProblems<TData = Awaited<ReturnType<typeof getProblems>>, TError = unknown>(
 lessonId: number,
    params: undefined |  GetProblemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblems>>,
          TError,
          Awaited<ReturnType<typeof getProblems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProblems<TData = Awaited<ReturnType<typeof getProblems>>, TError = unknown>(
 lessonId: number,
    params?: GetProblemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProblems>>,
          TError,
          Awaited<ReturnType<typeof getProblems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProblems<TData = Awaited<ReturnType<typeof getProblems>>, TError = unknown>(
 lessonId: number,
    params?: GetProblemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 레슨의 문제 목록
 */

export function useGetProblems<TData = Awaited<ReturnType<typeof getProblems>>, TError = unknown>(
 lessonId: number,
    params?: GetProblemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProblems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProblemsQueryOptions(lessonId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






