/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  SendConsecutiveLearningWarningParams,
  SendInactivityParams,
  SendNewContentParams
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 토큰으로 식별된 <strong>본인</strong>에게 NEW_CONTENT 알림을 즉시 발송합니다.<br>🔐 <strong>Jwt 필요</strong> (수신자는 토큰의 유저로 결정됩니다)<br><strong>unitId</strong>: 딥링크 이동 대상이 되는 유닛 ID (FCM data의 targetId로 전달됩니다)<br>본인 기기에 FCM 토큰이 등록돼 있지 않으면 발송 없이 무시됩니다.
 * @summary [테스트] 새 콘텐츠 알림 발송
 */
export const sendNewContent = (
    params: SendNewContentParams,
 signal?: AbortSignal
) => {


      return customInstance<number>(
      {url: `/api/v1/test/notifications/new-content`, method: 'POST',
        params, signal
    },
      );
    }



export const getSendNewContentMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendNewContent>>, TError,{params: SendNewContentParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendNewContent>>, TError,{params: SendNewContentParams}, TContext> => {

const mutationKey = ['sendNewContent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendNewContent>>, {params: SendNewContentParams}> = (props) => {
          const {params} = props ?? {};

          return  sendNewContent(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendNewContentMutationResult = NonNullable<Awaited<ReturnType<typeof sendNewContent>>>

    export type SendNewContentMutationError = ErrorResponse

    /**
 * @summary [테스트] 새 콘텐츠 알림 발송
 */
export const useSendNewContent = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendNewContent>>, TError,{params: SendNewContentParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendNewContent>>,
        TError,
        {params: SendNewContentParams},
        TContext
      > => {
      return useMutation(getSendNewContentMutationOptions(options), queryClient);
    }
    /**
 * 토큰으로 식별된 <strong>본인</strong>에게 INACTIVITY 알림을 즉시 발송합니다.<br>🔐 <strong>Jwt 필요</strong> (수신자는 토큰의 유저로 결정됩니다)<br>미접속 일수 조건을 검사하지 않고 바로 발송합니다.<br><strong>inactiveDays</strong>: 메시지를 결정하는 미접속 일수. 7 / 14 / 30 / 60 / 90 은 전용 문구가 매칭되며, 그 외 값은 기본 문구가 사용됩니다.<br>본인 기기에 FCM 토큰이 등록돼 있지 않으면 발송 없이 무시됩니다.
 * @summary [테스트] 장기 미접속 알림 발송
 */
export const sendInactivity = (
    params?: SendInactivityParams,
 signal?: AbortSignal
) => {


      return customInstance<number>(
      {url: `/api/v1/test/notifications/inactivity`, method: 'POST',
        params, signal
    },
      );
    }



export const getSendInactivityMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendInactivity>>, TError,{params?: SendInactivityParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendInactivity>>, TError,{params?: SendInactivityParams}, TContext> => {

const mutationKey = ['sendInactivity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendInactivity>>, {params?: SendInactivityParams}> = (props) => {
          const {params} = props ?? {};

          return  sendInactivity(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendInactivityMutationResult = NonNullable<Awaited<ReturnType<typeof sendInactivity>>>

    export type SendInactivityMutationError = ErrorResponse

    /**
 * @summary [테스트] 장기 미접속 알림 발송
 */
export const useSendInactivity = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendInactivity>>, TError,{params?: SendInactivityParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendInactivity>>,
        TError,
        {params?: SendInactivityParams},
        TContext
      > => {
      return useMutation(getSendInactivityMutationOptions(options), queryClient);
    }
    /**
 * 토큰으로 식별된 <strong>본인</strong>에게 DAILY_INCOMPLETE 알림을 즉시 발송합니다.<br>🔐 <strong>Jwt 필요</strong> (수신자는 토큰의 유저로 결정됩니다)<br>학습 미완료 조건을 검사하지 않고 바로 발송합니다.<br>메시지는 사전 정의된 문구 중 무작위로 선택됩니다.<br>본인 기기에 FCM 토큰이 등록돼 있지 않으면 발송 없이 무시됩니다.
 * @summary [테스트] 오늘 학습 미완료 알림 발송
 */
export const sendDailyIncomplete = (

 signal?: AbortSignal
) => {


      return customInstance<number>(
      {url: `/api/v1/test/notifications/daily-incomplete`, method: 'POST', signal
    },
      );
    }



export const getSendDailyIncompleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendDailyIncomplete>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendDailyIncomplete>>, TError,void, TContext> => {

const mutationKey = ['sendDailyIncomplete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendDailyIncomplete>>, void> = () => {


          return  sendDailyIncomplete()
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendDailyIncompleteMutationResult = NonNullable<Awaited<ReturnType<typeof sendDailyIncomplete>>>

    export type SendDailyIncompleteMutationError = ErrorResponse

    /**
 * @summary [테스트] 오늘 학습 미완료 알림 발송
 */
export const useSendDailyIncomplete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendDailyIncomplete>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendDailyIncomplete>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSendDailyIncompleteMutationOptions(options), queryClient);
    }
    /**
 * 토큰으로 식별된 <strong>본인</strong>에게 CONSECUTIVE_LEARNING_WARNING 알림을 즉시 발송합니다.<br>🔐 <strong>Jwt 필요</strong> (수신자는 토큰의 유저로 결정되며, 별도 userId를 받지 않습니다)<br>연속학습 일수 조건을 검사하지 않고 바로 발송합니다.<br><strong>consecutiveDays</strong>: 메시지에 표시될 연속학습 일수 (예: 3 → "오늘 학습을 하지 않으면 3일 연속학습이 끊겨요!")<br>본인 기기에 FCM 토큰이 등록돼 있지 않으면 발송 없이 무시됩니다.
 * @summary [테스트] 연속학습 끊길 위기 알림 발송
 */
export const sendConsecutiveLearningWarning = (
    params?: SendConsecutiveLearningWarningParams,
 signal?: AbortSignal
) => {


      return customInstance<number>(
      {url: `/api/v1/test/notifications/consecutive-learning-warning`, method: 'POST',
        params, signal
    },
      );
    }



export const getSendConsecutiveLearningWarningMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>, TError,{params?: SendConsecutiveLearningWarningParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>, TError,{params?: SendConsecutiveLearningWarningParams}, TContext> => {

const mutationKey = ['sendConsecutiveLearningWarning'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>, {params?: SendConsecutiveLearningWarningParams}> = (props) => {
          const {params} = props ?? {};

          return  sendConsecutiveLearningWarning(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendConsecutiveLearningWarningMutationResult = NonNullable<Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>>

    export type SendConsecutiveLearningWarningMutationError = ErrorResponse

    /**
 * @summary [테스트] 연속학습 끊길 위기 알림 발송
 */
export const useSendConsecutiveLearningWarning = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>, TError,{params?: SendConsecutiveLearningWarningParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendConsecutiveLearningWarning>>,
        TError,
        {params?: SendConsecutiveLearningWarningParams},
        TContext
      > => {
      return useMutation(getSendConsecutiveLearningWarningMutationOptions(options), queryClient);
    }
