/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { ProblemCreateRequest } from '../models';
// @ts-ignore
import type { ProblemResponse } from '../models';
// @ts-ignore
import type { ProblemUpdateRequest } from '../models';
/**
 * AdminProblemAPIApi - axios parameter creator
 */
export const AdminProblemAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 새로운 문제를 생성합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 생성
         * @param {ProblemCreateRequest} problemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProblem: async (problemCreateRequest: ProblemCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'problemCreateRequest' is not null or undefined
            assertParamExists('createProblem', 'problemCreateRequest', problemCreateRequest)
            const localVarPath = `/api/v1/admin/problems`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(problemCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 문제를 삭제합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 삭제
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProblem: async (problemId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'problemId' is not null or undefined
            assertParamExists('deleteProblem', 'problemId', problemId)
            const localVarPath = `/api/v1/admin/problems/{problemId}`
                .replace(`{${"problemId"}}`, encodeURIComponent(String(problemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 문제의 상세 정보를 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 조회
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProblem: async (problemId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'problemId' is not null or undefined
            assertParamExists('getProblem', 'problemId', problemId)
            const localVarPath = `/api/v1/admin/problems/{problemId}`
                .replace(`{${"problemId"}}`, encodeURIComponent(String(problemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 문제를 수정합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 수정
         * @param {ProblemUpdateRequest} problemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProblem: async (problemUpdateRequest: ProblemUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'problemUpdateRequest' is not null or undefined
            assertParamExists('updateProblem', 'problemUpdateRequest', problemUpdateRequest)
            const localVarPath = `/api/v1/admin/problems`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(problemUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminProblemAPIApi - functional programming interface
 */
export const AdminProblemAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminProblemAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 새로운 문제를 생성합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 생성
         * @param {ProblemCreateRequest} problemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProblem(problemCreateRequest: ProblemCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProblem(problemCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminProblemAPIApi.createProblem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 문제를 삭제합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 삭제
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProblem(problemId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProblem(problemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminProblemAPIApi.deleteProblem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 문제의 상세 정보를 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 조회
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProblem(problemId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProblemResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProblem(problemId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminProblemAPIApi.getProblem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 문제를 수정합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 수정
         * @param {ProblemUpdateRequest} problemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProblem(problemUpdateRequest: ProblemUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProblem(problemUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminProblemAPIApi.updateProblem']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminProblemAPIApi - factory interface
 */
export const AdminProblemAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminProblemAPIApiFp(configuration)
    return {
        /**
         * 새로운 문제를 생성합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 생성
         * @param {ProblemCreateRequest} problemCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProblem(problemCreateRequest: ProblemCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createProblem(problemCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 문제를 삭제합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 삭제
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProblem(problemId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteProblem(problemId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 문제의 상세 정보를 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 조회
         * @param {number} problemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProblem(problemId: number, options?: RawAxiosRequestConfig): AxiosPromise<ProblemResponse> {
            return localVarFp.getProblem(problemId, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 문제를 수정합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
         * @summary 문제 수정
         * @param {ProblemUpdateRequest} problemUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProblem(problemUpdateRequest: ProblemUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateProblem(problemUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminProblemAPIApi - object-oriented interface
 */
export class AdminProblemAPIApi extends BaseAPI {
    /**
     * 새로운 문제를 생성합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
     * @summary 문제 생성
     * @param {ProblemCreateRequest} problemCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProblem(problemCreateRequest: ProblemCreateRequest, options?: RawAxiosRequestConfig) {
        return AdminProblemAPIApiFp(this.configuration).createProblem(problemCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 문제를 삭제합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
     * @summary 문제 삭제
     * @param {number} problemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteProblem(problemId: number, options?: RawAxiosRequestConfig) {
        return AdminProblemAPIApiFp(this.configuration).deleteProblem(problemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 문제의 상세 정보를 조회합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
     * @summary 문제 조회
     * @param {number} problemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProblem(problemId: number, options?: RawAxiosRequestConfig) {
        return AdminProblemAPIApiFp(this.configuration).getProblem(problemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 문제를 수정합니다<br>🔐 <strong>관리자 권한 필요</strong><br>
     * @summary 문제 수정
     * @param {ProblemUpdateRequest} problemUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateProblem(problemUpdateRequest: ProblemUpdateRequest, options?: RawAxiosRequestConfig) {
        return AdminProblemAPIApiFp(this.configuration).updateProblem(problemUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

