/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminNoticeDetailResponse } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { PageResponse } from '../models';
/**
 * AdminNoticeQueryAPIApi - axios parameter creator
 */
export const AdminNoticeQueryAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 공지 단건을 조회합니다. <strong>DRAFT</strong> 상태도 조회 가능하며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 어드민 공지 단건 조회
         * @param {number} noticeId 조회할 공지 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNoticeByAdmin: async (noticeId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'noticeId' is not null or undefined
            assertParamExists('getNoticeByAdmin', 'noticeId', noticeId)
            const localVarPath = `/api/v1/admin/notice/{noticeId}`
                .replace(`{${"noticeId"}}`, encodeURIComponent(String(noticeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 공지 요약 목록을 조회합니다. <strong>DRAFT, PUBLISHED</strong> 모두 포함되며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong><br> 
         * @summary 어드민 공지 목록(요약) 조회
         * @param {number} page 1부터 시작하는 페이지 번호
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNoticeSummaryByAdmin: async (page: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getNoticeSummaryByAdmin', 'page', page)
            const localVarPath = `/api/v1/admin/notice/summaries/{page}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminNoticeQueryAPIApi - functional programming interface
 */
export const AdminNoticeQueryAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminNoticeQueryAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 공지 단건을 조회합니다. <strong>DRAFT</strong> 상태도 조회 가능하며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 어드민 공지 단건 조회
         * @param {number} noticeId 조회할 공지 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNoticeByAdmin(noticeId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminNoticeDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNoticeByAdmin(noticeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminNoticeQueryAPIApi.getNoticeByAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 공지 요약 목록을 조회합니다. <strong>DRAFT, PUBLISHED</strong> 모두 포함되며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong><br> 
         * @summary 어드민 공지 목록(요약) 조회
         * @param {number} page 1부터 시작하는 페이지 번호
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNoticeSummaryByAdmin(page: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNoticeSummaryByAdmin(page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminNoticeQueryAPIApi.getNoticeSummaryByAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminNoticeQueryAPIApi - factory interface
 */
export const AdminNoticeQueryAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminNoticeQueryAPIApiFp(configuration)
    return {
        /**
         * 공지 단건을 조회합니다. <strong>DRAFT</strong> 상태도 조회 가능하며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong> 
         * @summary 어드민 공지 단건 조회
         * @param {number} noticeId 조회할 공지 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNoticeByAdmin(noticeId: number, options?: RawAxiosRequestConfig): AxiosPromise<AdminNoticeDetailResponse> {
            return localVarFp.getNoticeByAdmin(noticeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 공지 요약 목록을 조회합니다. <strong>DRAFT, PUBLISHED</strong> 모두 포함되며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong><br> 
         * @summary 어드민 공지 목록(요약) 조회
         * @param {number} page 1부터 시작하는 페이지 번호
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNoticeSummaryByAdmin(page: number, options?: RawAxiosRequestConfig): AxiosPromise<PageResponse> {
            return localVarFp.getNoticeSummaryByAdmin(page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminNoticeQueryAPIApi - object-oriented interface
 */
export class AdminNoticeQueryAPIApi extends BaseAPI {
    /**
     * 공지 단건을 조회합니다. <strong>DRAFT</strong> 상태도 조회 가능하며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong> 
     * @summary 어드민 공지 단건 조회
     * @param {number} noticeId 조회할 공지 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNoticeByAdmin(noticeId: number, options?: RawAxiosRequestConfig) {
        return AdminNoticeQueryAPIApiFp(this.configuration).getNoticeByAdmin(noticeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 공지 요약 목록을 조회합니다. <strong>DRAFT, PUBLISHED</strong> 모두 포함되며, ADMIN 권한이 필요합니다.<br> 🔐 <strong>Jwt 필요</strong><br> 
     * @summary 어드민 공지 목록(요약) 조회
     * @param {number} page 1부터 시작하는 페이지 번호
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNoticeSummaryByAdmin(page: number, options?: RawAxiosRequestConfig) {
        return AdminNoticeQueryAPIApiFp(this.configuration).getNoticeSummaryByAdmin(page, options).then((request) => request(this.axios, this.basePath));
    }
}

