/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUsersParams,
  PageResponseUserListItemResponse,
  UserDetailResponse,
  UserRoleUpdateRequest,
  UserStatusUpdateRequest
} from '../model';

import { customInstance } from '../../mutator';




/**
 * ACTIVE/SUSPENDED/DELETED. 감사 로그 기록.
 * @summary 유저 상태 변경
 */
export const updateStatus = (
    userId: number,
    userStatusUpdateRequest: UserStatusUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/users/${userId}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userStatusUpdateRequest, signal
    },
      );
    }



export const getUpdateStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{userId: number;data: UserStatusUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{userId: number;data: UserStatusUpdateRequest}, TContext> => {

const mutationKey = ['updateStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStatus>>, {userId: number;data: UserStatusUpdateRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateStatus(userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateStatus>>>
    export type UpdateStatusMutationBody = UserStatusUpdateRequest
    export type UpdateStatusMutationError = void

    /**
 * @summary 유저 상태 변경
 */
export const useUpdateStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStatus>>, TError,{userId: number;data: UserStatusUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStatus>>,
        TError,
        {userId: number;data: UserStatusUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateStatusMutationOptions(options), queryClient);
    }
    /**
 * ADMIN/USER. 감사 로그 기록.
 * @summary 유저 권한 변경
 */
export const updateRole = (
    userId: number,
    userRoleUpdateRequest: UserRoleUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/users/${userId}/role`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userRoleUpdateRequest, signal
    },
      );
    }



export const getUpdateRoleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext> => {

const mutationKey = ['updateRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRole>>, {userId: number;data: UserRoleUpdateRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateRole(userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateRole>>>
    export type UpdateRoleMutationBody = UserRoleUpdateRequest
    export type UpdateRoleMutationError = void

    /**
 * @summary 유저 권한 변경
 */
export const useUpdateRole = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRole>>,
        TError,
        {userId: number;data: UserRoleUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateRoleMutationOptions(options), queryClient);
    }
    /**
 * search(email/nickname/handle 부분일치)·status·role 필터, 1-based page, size 20 고정.
 * @summary 유저 목록
 */
export const getUsers = (
    params?: GetUsersParams,
 signal?: AbortSignal
) => {


      return customInstance<PageResponseUserListItemResponse>(
      {url: `/api/v1/admin/users`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetUsersQueryKey = (params?: GetUsersParams,) => {
    return [
    `/api/v1/admin/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = unknown


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params: undefined |  GetUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유저 목록
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 유저 상세
 */
export const getUser1 = (
    userId: number,
 signal?: AbortSignal
) => {


      return customInstance<UserDetailResponse>(
      {url: `/api/v1/admin/users/${userId}`, method: 'GET', signal
    },
      );
    }




export const getGetUser1QueryKey = (userId: number,) => {
    return [
    `/api/v1/admin/users/${userId}`
    ] as const;
    }


export const getGetUser1QueryOptions = <TData = Awaited<ReturnType<typeof getUser1>>, TError = UserDetailResponse>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUser1QueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser1>>> = ({ signal }) => getUser1(userId, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUser1QueryResult = NonNullable<Awaited<ReturnType<typeof getUser1>>>
export type GetUser1QueryError = UserDetailResponse


export function useGetUser1<TData = Awaited<ReturnType<typeof getUser1>>, TError = UserDetailResponse>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser1>>,
          TError,
          Awaited<ReturnType<typeof getUser1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser1<TData = Awaited<ReturnType<typeof getUser1>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser1>>,
          TError,
          Awaited<ReturnType<typeof getUser1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser1<TData = Awaited<ReturnType<typeof getUser1>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유저 상세
 */

export function useGetUser1<TData = Awaited<ReturnType<typeof getUser1>>, TError = UserDetailResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUser1QueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






