/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  LessonResponse
} from '../model';


export const getGetAllProblemInLessonResponseMock = (overrideResponse: Partial<Extract<LessonResponse, object>> = {}): LessonResponse => ({unitSummaryResponse: {unitId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}})}, problems: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({problemId: faker.helpers.arrayElement([faker.number.int(), undefined]), problemType: faker.helpers.arrayElement(['SUBJECTIVE','OBJECTIVE'] as const), instruction: faker.string.alpha({length: {min: 10, max: 20}}), content: faker.string.alpha({length: {min: 10, max: 20}}), answerResponse: faker.helpers.arrayElement([{contents: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), explanation: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), options: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({optionId: faker.helpers.arrayElement([faker.number.int(), undefined]), content: faker.string.alpha({length: {min: 10, max: 20}}), explanation: faker.string.alpha({length: {min: 10, max: 20}}), isAnswer: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), problemId: faker.helpers.arrayElement([faker.number.int(), undefined])})), undefined]), isBookmarked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})), totalProblems: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})


export const getSaveProblemSubmissionMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/problems/results', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetAllProblemInLessonMockHandler = (overrideResponse?: LessonResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LessonResponse> | LessonResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/problems/:lessonId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllProblemInLessonResponseMock(),
      { status: 200
      })
  }, options)
}
export const getProblemApiMock = () => [
  getSaveProblemSubmissionMockHandler(),
  getGetAllProblemInLessonMockHandler()
]
