/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';
import {
  useMutation
} from '@tanstack/react-query';

import { customInstance } from '../../mutator';
import type {
  ErrorResponse,
  IdTokenRequest,
  LoginResponse,
  NaverAndroidUserInfoRequest,
  OauthLogin1Params
} from '../model';




/**
 * Android 에서 전달한 OAuth IdToken 및 provider 기반으로 사용자 정보를 조회하고 회원가입/로그인 처리를 합니다. <br>google, kakao 만 해당 api로 로그인 할 수 있습니다(IdToken 방식)IdToken 을 body에 담고, provider는 쿼리 파라미터로 담아서 사용합니다.
 * @summary OAuth 회원가입/로그인 처리
 */
export const oauthLogin1 = (
    idTokenRequest: IdTokenRequest,
    params: OauthLogin1Params,
 signal?: AbortSignal
) => {


      return customInstance<LoginResponse>(
      {url: `/api/v1/oauth/android`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idTokenRequest,
        params, signal
    },
      );
    }



export const getOauthLogin1MutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthLogin1>>, TError,{data: IdTokenRequest;params: OauthLogin1Params}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof oauthLogin1>>, TError,{data: IdTokenRequest;params: OauthLogin1Params}, TContext> => {

const mutationKey = ['oauthLogin1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof oauthLogin1>>, {data: IdTokenRequest;params: OauthLogin1Params}> = (props) => {
          const {data,params} = props ?? {};

          return  oauthLogin1(data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OauthLogin1MutationResult = NonNullable<Awaited<ReturnType<typeof oauthLogin1>>>
    export type OauthLogin1MutationBody = IdTokenRequest
    export type OauthLogin1MutationError = ErrorResponse

    /**
 * @summary OAuth 회원가입/로그인 처리
 */
export const useOauthLogin1 = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthLogin1>>, TError,{data: IdTokenRequest;params: OauthLogin1Params}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof oauthLogin1>>,
        TError,
        {data: IdTokenRequest;params: OauthLogin1Params},
        TContext
      > => {
      return useMutation(getOauthLogin1MutationOptions(options), queryClient);
    }
    /**
 * Android에서 전달한 네이버 사용자 정보를 기반으로 회원가입/로그인 처리를 합니다. <br>네이버는 IdToken 방식을 지원하지 않기 때문에 Android에서 직접 사용자 정보(providerId, email, nickname)를 전달합니다.
 * @summary 네이버 OAuth 회원가입/로그인 처리
 */
export const oauthNaverLogin = (
    naverAndroidUserInfoRequest: NaverAndroidUserInfoRequest,
 signal?: AbortSignal
) => {


      return customInstance<LoginResponse>(
      {url: `/api/v1/oauth/android/naver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: naverAndroidUserInfoRequest, signal
    },
      );
    }



export const getOauthNaverLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthNaverLogin>>, TError,{data: NaverAndroidUserInfoRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof oauthNaverLogin>>, TError,{data: NaverAndroidUserInfoRequest}, TContext> => {

const mutationKey = ['oauthNaverLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof oauthNaverLogin>>, {data: NaverAndroidUserInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  oauthNaverLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OauthNaverLoginMutationResult = NonNullable<Awaited<ReturnType<typeof oauthNaverLogin>>>
    export type OauthNaverLoginMutationBody = NaverAndroidUserInfoRequest
    export type OauthNaverLoginMutationError = ErrorResponse

    /**
 * @summary 네이버 OAuth 회원가입/로그인 처리
 */
export const useOauthNaverLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthNaverLogin>>, TError,{data: NaverAndroidUserInfoRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof oauthNaverLogin>>,
        TError,
        {data: NaverAndroidUserInfoRequest},
        TContext
      > => {
      return useMutation(getOauthNaverLoginMutationOptions(options), queryClient);
    }
