/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookmarkDeleteRequest,
  BookmarkSaveRequest,
  BookmarkedProblemResponse,
  ErrorResponse
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 특정 문제를 북마크에 추가합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 북마크 저장
 */
export const addBookmark = (
    bookmarkSaveRequest: BookmarkSaveRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/bookmarks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bookmarkSaveRequest, signal
    },
      );
    }



export const getAddBookmarkMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addBookmark>>, TError,{data: BookmarkSaveRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addBookmark>>, TError,{data: BookmarkSaveRequest}, TContext> => {

const mutationKey = ['addBookmark'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addBookmark>>, {data: BookmarkSaveRequest}> = (props) => {
          const {data} = props ?? {};

          return  addBookmark(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddBookmarkMutationResult = NonNullable<Awaited<ReturnType<typeof addBookmark>>>
    export type AddBookmarkMutationBody = BookmarkSaveRequest
    export type AddBookmarkMutationError = ErrorResponse

    /**
 * @summary 북마크 저장
 */
export const useAddBookmark = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addBookmark>>, TError,{data: BookmarkSaveRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addBookmark>>,
        TError,
        {data: BookmarkSaveRequest},
        TContext
      > => {
      return useMutation(getAddBookmarkMutationOptions(options), queryClient);
    }
    /**
 * 특정 문제의 북마크를 삭제합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 북마크 삭제
 */
export const deleteBookmark = (
    bookmarkDeleteRequest: BookmarkDeleteRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/bookmarks`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: bookmarkDeleteRequest, signal
    },
      );
    }



export const getDeleteBookmarkMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBookmark>>, TError,{data: BookmarkDeleteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteBookmark>>, TError,{data: BookmarkDeleteRequest}, TContext> => {

const mutationKey = ['deleteBookmark'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBookmark>>, {data: BookmarkDeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  deleteBookmark(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBookmarkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBookmark>>>
    export type DeleteBookmarkMutationBody = BookmarkDeleteRequest
    export type DeleteBookmarkMutationError = ErrorResponse

    /**
 * @summary 북마크 삭제
 */
export const useDeleteBookmark = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBookmark>>, TError,{data: BookmarkDeleteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBookmark>>,
        TError,
        {data: BookmarkDeleteRequest},
        TContext
      > => {
      return useMutation(getDeleteBookmarkMutationOptions(options), queryClient);
    }
    /**
 * 특정 유닛에서 사용자가 북마크한 문제 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 유닛 내 북마크된 문제 조회
 */
export const getAllBookmarkedProblemInUnit = (
    unitId: number,
 signal?: AbortSignal
) => {


      return customInstance<BookmarkedProblemResponse>(
      {url: `/api/v1/bookmarks/${unitId}`, method: 'GET', signal
    },
      );
    }




export const getGetAllBookmarkedProblemInUnitQueryKey = (unitId: number,) => {
    return [
    `/api/v1/bookmarks/${unitId}`
    ] as const;
    }


export const getGetAllBookmarkedProblemInUnitQueryOptions = <TData = Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError = ErrorResponse>(unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBookmarkedProblemInUnitQueryKey(unitId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>> = ({ signal }) => getAllBookmarkedProblemInUnit(unitId, signal);





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBookmarkedProblemInUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>>
export type GetAllBookmarkedProblemInUnitQueryError = ErrorResponse


export function useGetAllBookmarkedProblemInUnit<TData = Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBookmarkedProblemInUnit<TData = Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBookmarkedProblemInUnit<TData = Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유닛 내 북마크된 문제 조회
 */

export function useGetAllBookmarkedProblemInUnit<TData = Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBookmarkedProblemInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBookmarkedProblemInUnitQueryOptions(unitId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






