/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  WrongAnsweredNoteDeleteRequest,
  WrongAnsweredProblemsResponse
} from '../model';

import { customInstance } from '../../mutator';




export type getAllWrongAnsweredProblemInUnitResponse200 = {
  data: WrongAnsweredProblemsResponse
  status: 200
}

export type getAllWrongAnsweredProblemInUnitResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAllWrongAnsweredProblemInUnitResponseSuccess = (getAllWrongAnsweredProblemInUnitResponse200) & {
  headers: Headers;
};
export type getAllWrongAnsweredProblemInUnitResponseError = (getAllWrongAnsweredProblemInUnitResponse404) & {
  headers: Headers;
};

export type getAllWrongAnsweredProblemInUnitResponse = (getAllWrongAnsweredProblemInUnitResponseSuccess | getAllWrongAnsweredProblemInUnitResponseError)

export const getGetAllWrongAnsweredProblemInUnitUrl = (unitId: number,) => {




  return `/api/v1/wrong-answered-notes/${unitId}`
}

/**
 * 특정 유닛에서 사용자가 틀린 문제 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 유닛 내 오답 문제 조회
 */
export const getAllWrongAnsweredProblemInUnit = async (unitId: number, options?: RequestInit): Promise<getAllWrongAnsweredProblemInUnitResponse> => {

  return customInstance<getAllWrongAnsweredProblemInUnitResponse>(getGetAllWrongAnsweredProblemInUnitUrl(unitId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllWrongAnsweredProblemInUnitQueryKey = (unitId: number,) => {
    return [
    `/api/v1/wrong-answered-notes/${unitId}`
    ] as const;
    }


export const getGetAllWrongAnsweredProblemInUnitQueryOptions = <TData = Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError = ErrorResponse>(unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllWrongAnsweredProblemInUnitQueryKey(unitId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>> = ({ signal }) => getAllWrongAnsweredProblemInUnit(unitId, { signal });





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllWrongAnsweredProblemInUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>>
export type GetAllWrongAnsweredProblemInUnitQueryError = ErrorResponse


export function useGetAllWrongAnsweredProblemInUnit<TData = Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWrongAnsweredProblemInUnit<TData = Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>,
          TError,
          Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllWrongAnsweredProblemInUnit<TData = Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유닛 내 오답 문제 조회
 */

export function useGetAllWrongAnsweredProblemInUnit<TData = Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError = ErrorResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllWrongAnsweredProblemInUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllWrongAnsweredProblemInUnitQueryOptions(unitId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteWrongAnsweredProblemResponse204 = {
  data: void
  status: 204
}

export type deleteWrongAnsweredProblemResponseSuccess = (deleteWrongAnsweredProblemResponse204) & {
  headers: Headers;
};
;

export type deleteWrongAnsweredProblemResponse = (deleteWrongAnsweredProblemResponseSuccess)

export const getDeleteWrongAnsweredProblemUrl = () => {




  return `/api/v1/wrong-answered-notes`
}

/**
 * 특정 문제의 오답노트를 삭제합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 오답노트 삭제
 */
export const deleteWrongAnsweredProblem = async (wrongAnsweredNoteDeleteRequest: WrongAnsweredNoteDeleteRequest, options?: RequestInit): Promise<deleteWrongAnsweredProblemResponse> => {

  return customInstance<deleteWrongAnsweredProblemResponse>(getDeleteWrongAnsweredProblemUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(wrongAnsweredNoteDeleteRequest)
  }
);}




export const getDeleteWrongAnsweredProblemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>, TError,{data: WrongAnsweredNoteDeleteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>, TError,{data: WrongAnsweredNoteDeleteRequest}, TContext> => {

const mutationKey = ['deleteWrongAnsweredProblem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>, {data: WrongAnsweredNoteDeleteRequest}> = (props) => {
          const {data} = props ?? {};

          return  deleteWrongAnsweredProblem(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteWrongAnsweredProblemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>>
    export type DeleteWrongAnsweredProblemMutationBody = WrongAnsweredNoteDeleteRequest
    export type DeleteWrongAnsweredProblemMutationError = unknown

    /**
 * @summary 오답노트 삭제
 */
export const useDeleteWrongAnsweredProblem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>, TError,{data: WrongAnsweredNoteDeleteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWrongAnsweredProblem>>,
        TError,
        {data: WrongAnsweredNoteDeleteRequest},
        TContext
      > => {
      return useMutation(getDeleteWrongAnsweredProblemMutationOptions(options), queryClient);
    }
