/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AdminNoticeDetailResponse
} from '../model';


export const getCreateNoticeResponseMock = (overrideResponse: Partial<Extract<AdminNoticeDetailResponse, object>> = {}): AdminNoticeDetailResponse => ({noticeId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), contents: faker.string.alpha({length: {min: 10, max: 20}}), authorName: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', noticeType: faker.string.alpha({length: {min: 10, max: 20}}), pinned: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), publishedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})

export const getUpdateNoticeResponseMock = (overrideResponse: Partial<Extract<AdminNoticeDetailResponse, object>> = {}): AdminNoticeDetailResponse => ({noticeId: faker.helpers.arrayElement([faker.number.int(), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), contents: faker.string.alpha({length: {min: 10, max: 20}}), authorName: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', noticeType: faker.string.alpha({length: {min: 10, max: 20}}), pinned: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), publishedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), ...overrideResponse})


export const getCreateNoticeMockHandler = (overrideResponse?: AdminNoticeDetailResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AdminNoticeDetailResponse> | AdminNoticeDetailResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/admin/notice', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateNoticeResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateNoticeMockHandler = (overrideResponse?: AdminNoticeDetailResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<AdminNoticeDetailResponse> | AdminNoticeDetailResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/admin/notice', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateNoticeResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteNoticeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/admin/notice/:noticeId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getAdminNoticeCommandApiMock = () => [
  getCreateNoticeMockHandler(),
  getUpdateNoticeMockHandler(),
  getDeleteNoticeMockHandler()
]
