/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AllBadgesResponse
} from '../model';


export const getGetAllMyBadgesResponseMock = (overrideResponse: Partial<Extract<AllBadgesResponse, object>> = {}): AllBadgesResponse => ({earnedCount: faker.helpers.arrayElement([faker.number.int(), undefined]), totalCount: faker.helpers.arrayElement([faker.number.int(), undefined]), badgeCategoryResponses: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({categoryId: faker.helpers.arrayElement([faker.number.int(), undefined]), categoryName: faker.string.alpha({length: {min: 10, max: 20}}), order: faker.helpers.arrayElement([faker.number.int(), undefined]), categoryDescription: faker.string.alpha({length: {min: 10, max: 20}}), badgeResponses: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({badgeId: faker.helpers.arrayElement([faker.number.int(), undefined]), code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), order: faker.helpers.arrayElement([faker.number.int(), undefined]), iconId: faker.helpers.arrayElement([faker.number.int(), undefined]), earned: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}))})), ...overrideResponse})


export const getGetAllMyBadgesMockHandler = (overrideResponse?: AllBadgesResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AllBadgesResponse> | AllBadgesResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/badges/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllMyBadgesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getBadgeMock = () => [
  getGetAllMyBadgesMockHandler()
]
