/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLabelsParams,
  LabelStatusUpdateRequest,
  PageResponseStagingLabelListItemResponse,
  StagingAnswerUpdateRequest,
  StagingLabelDetailResponse,
  StagingLessonUpdateRequest,
  StagingOptionUpdateRequest,
  StagingProblemUpdateRequest
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 라벨이 COMPLETED 면 409.
 * @summary 스테이징 문제 수정 (부분)
 */
export const updateProblem = (
    problemId: number,
    stagingProblemUpdateRequest: StagingProblemUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/staging/problems/${problemId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: stagingProblemUpdateRequest, signal
    },
      );
    }



export const getUpdateProblemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProblem>>, TError,{problemId: number;data: StagingProblemUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProblem>>, TError,{problemId: number;data: StagingProblemUpdateRequest}, TContext> => {

const mutationKey = ['updateProblem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProblem>>, {problemId: number;data: StagingProblemUpdateRequest}> = (props) => {
          const {problemId,data} = props ?? {};

          return  updateProblem(problemId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProblemMutationResult = NonNullable<Awaited<ReturnType<typeof updateProblem>>>
    export type UpdateProblemMutationBody = StagingProblemUpdateRequest
    export type UpdateProblemMutationError = void

    /**
 * @summary 스테이징 문제 수정 (부분)
 */
export const useUpdateProblem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProblem>>, TError,{problemId: number;data: StagingProblemUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProblem>>,
        TError,
        {problemId: number;data: StagingProblemUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateProblemMutationOptions(options), queryClient);
    }
    /**
 * 라벨이 COMPLETED 면 409.
 * @summary 스테이징 옵션 수정 (부분)
 */
export const updateOption = (
    optionId: number,
    stagingOptionUpdateRequest: StagingOptionUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/staging/options/${optionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: stagingOptionUpdateRequest, signal
    },
      );
    }



export const getUpdateOptionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOption>>, TError,{optionId: number;data: StagingOptionUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOption>>, TError,{optionId: number;data: StagingOptionUpdateRequest}, TContext> => {

const mutationKey = ['updateOption'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOption>>, {optionId: number;data: StagingOptionUpdateRequest}> = (props) => {
          const {optionId,data} = props ?? {};

          return  updateOption(optionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOptionMutationResult = NonNullable<Awaited<ReturnType<typeof updateOption>>>
    export type UpdateOptionMutationBody = StagingOptionUpdateRequest
    export type UpdateOptionMutationError = void

    /**
 * @summary 스테이징 옵션 수정 (부분)
 */
export const useUpdateOption = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOption>>, TError,{optionId: number;data: StagingOptionUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOption>>,
        TError,
        {optionId: number;data: StagingOptionUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateOptionMutationOptions(options), queryClient);
    }
    /**
 * 라벨이 COMPLETED 면 409.
 * @summary 스테이징 레슨 수정
 */
export const updateLesson = (
    lessonId: number,
    stagingLessonUpdateRequest: StagingLessonUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/staging/lessons/${lessonId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: stagingLessonUpdateRequest, signal
    },
      );
    }



export const getUpdateLessonMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{lessonId: number;data: StagingLessonUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{lessonId: number;data: StagingLessonUpdateRequest}, TContext> => {

const mutationKey = ['updateLesson'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLesson>>, {lessonId: number;data: StagingLessonUpdateRequest}> = (props) => {
          const {lessonId,data} = props ?? {};

          return  updateLesson(lessonId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLessonMutationResult = NonNullable<Awaited<ReturnType<typeof updateLesson>>>
    export type UpdateLessonMutationBody = StagingLessonUpdateRequest
    export type UpdateLessonMutationError = void

    /**
 * @summary 스테이징 레슨 수정
 */
export const useUpdateLesson = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLesson>>, TError,{lessonId: number;data: StagingLessonUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLesson>>,
        TError,
        {lessonId: number;data: StagingLessonUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateLessonMutationOptions(options), queryClient);
    }
    /**
 * status=COMPLETED 로 staging->prod 전환. 비가역. 감사 로그 기록.
 * @summary 스테이징 라벨 승급(promote)
 */
export const promote = (
    label: string,
    labelStatusUpdateRequest: LabelStatusUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/staging/labels/${label}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: labelStatusUpdateRequest, signal
    },
      );
    }



export const getPromoteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof promote>>, TError,{label: string;data: LabelStatusUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof promote>>, TError,{label: string;data: LabelStatusUpdateRequest}, TContext> => {

const mutationKey = ['promote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof promote>>, {label: string;data: LabelStatusUpdateRequest}> = (props) => {
          const {label,data} = props ?? {};

          return  promote(label,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PromoteMutationResult = NonNullable<Awaited<ReturnType<typeof promote>>>
    export type PromoteMutationBody = LabelStatusUpdateRequest
    export type PromoteMutationError = void

    /**
 * @summary 스테이징 라벨 승급(promote)
 */
export const usePromote = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof promote>>, TError,{label: string;data: LabelStatusUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof promote>>,
        TError,
        {label: string;data: LabelStatusUpdateRequest},
        TContext
      > => {
      return useMutation(getPromoteMutationOptions(options), queryClient);
    }
    /**
 * 라벨이 COMPLETED 면 409.
 * @summary 스테이징 정답 수정 (부분)
 */
export const updateAnswer = (
    answerId: number,
    stagingAnswerUpdateRequest: StagingAnswerUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/staging/answers/${answerId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: stagingAnswerUpdateRequest, signal
    },
      );
    }



export const getUpdateAnswerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{answerId: number;data: StagingAnswerUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{answerId: number;data: StagingAnswerUpdateRequest}, TContext> => {

const mutationKey = ['updateAnswer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAnswer>>, {answerId: number;data: StagingAnswerUpdateRequest}> = (props) => {
          const {answerId,data} = props ?? {};

          return  updateAnswer(answerId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof updateAnswer>>>
    export type UpdateAnswerMutationBody = StagingAnswerUpdateRequest
    export type UpdateAnswerMutationError = void

    /**
 * @summary 스테이징 정답 수정 (부분)
 */
export const useUpdateAnswer = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{answerId: number;data: StagingAnswerUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAnswer>>,
        TError,
        {answerId: number;data: StagingAnswerUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateAnswerMutationOptions(options), queryClient);
    }
    /**
 * status(PENDING/COMPLETED) 필터.
 * @summary 스테이징 라벨 목록
 */
export const getLabels = (
    params?: GetLabelsParams,
 signal?: AbortSignal
) => {


      return customInstance<PageResponseStagingLabelListItemResponse>(
      {url: `/api/v1/admin/staging/labels`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLabelsQueryKey = (params?: GetLabelsParams,) => {
    return [
    `/api/v1/admin/staging/labels`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLabelsQueryOptions = <TData = Awaited<ReturnType<typeof getLabels>>, TError = unknown>(params?: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLabelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabels>>> = ({ signal }) => getLabels(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelsQueryResult = NonNullable<Awaited<ReturnType<typeof getLabels>>>
export type GetLabelsQueryError = unknown


export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = unknown>(
 params: undefined |  GetLabelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabels>>,
          TError,
          Awaited<ReturnType<typeof getLabels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = unknown>(
 params?: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabels>>,
          TError,
          Awaited<ReturnType<typeof getLabels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = unknown>(
 params?: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 스테이징 라벨 목록
 */

export function useGetLabels<TData = Awaited<ReturnType<typeof getLabels>>, TError = unknown>(
 params?: GetLabelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabels>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLabelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * lesson + problems(options|answer) 그루핑.
 * @summary 스테이징 라벨 상세
 */
export const getLabelDetail = (
    label: string,
 signal?: AbortSignal
) => {


      return customInstance<StagingLabelDetailResponse>(
      {url: `/api/v1/admin/staging/labels/${label}`, method: 'GET', signal
    },
      );
    }




export const getGetLabelDetailQueryKey = (label: string,) => {
    return [
    `/api/v1/admin/staging/labels/${label}`
    ] as const;
    }


export const getGetLabelDetailQueryOptions = <TData = Awaited<ReturnType<typeof getLabelDetail>>, TError = StagingLabelDetailResponse>(label: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLabelDetailQueryKey(label);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabelDetail>>> = ({ signal }) => getLabelDetail(label, signal);





   return  { queryKey, queryFn, enabled: label !== null && label !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getLabelDetail>>>
export type GetLabelDetailQueryError = StagingLabelDetailResponse


export function useGetLabelDetail<TData = Awaited<ReturnType<typeof getLabelDetail>>, TError = StagingLabelDetailResponse>(
 label: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelDetail>>,
          TError,
          Awaited<ReturnType<typeof getLabelDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelDetail<TData = Awaited<ReturnType<typeof getLabelDetail>>, TError = StagingLabelDetailResponse>(
 label: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelDetail>>,
          TError,
          Awaited<ReturnType<typeof getLabelDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelDetail<TData = Awaited<ReturnType<typeof getLabelDetail>>, TError = StagingLabelDetailResponse>(
 label: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 스테이징 라벨 상세
 */

export function useGetLabelDetail<TData = Awaited<ReturnType<typeof getLabelDetail>>, TError = StagingLabelDetailResponse>(
 label: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLabelDetailQueryOptions(label,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






