/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ProblemReportSubmitRequest
} from '../model';

import { customInstance } from '../../mutator';




export type submitProblemReportResponse200 = {
  data: void
  status: 200
}

export type submitProblemReportResponse404 = {
  data: ErrorResponse
  status: 404
}

export type submitProblemReportResponseSuccess = (submitProblemReportResponse200) & {
  headers: Headers;
};
export type submitProblemReportResponseError = (submitProblemReportResponse404) & {
  headers: Headers;
};

export type submitProblemReportResponse = (submitProblemReportResponseSuccess | submitProblemReportResponseError)

export const getSubmitProblemReportUrl = () => {




  return `/api/v1/reports`
}

/**
 * 특정 문제에 대한 오류를 신고합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 문제 신고 제출
 */
export const submitProblemReport = async (problemReportSubmitRequest: ProblemReportSubmitRequest, options?: RequestInit): Promise<submitProblemReportResponse> => {

  return customInstance<submitProblemReportResponse>(getSubmitProblemReportUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(problemReportSubmitRequest)
  }
);}




export const getSubmitProblemReportMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitProblemReport>>, TError,{data: ProblemReportSubmitRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof submitProblemReport>>, TError,{data: ProblemReportSubmitRequest}, TContext> => {

const mutationKey = ['submitProblemReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitProblemReport>>, {data: ProblemReportSubmitRequest}> = (props) => {
          const {data} = props ?? {};

          return  submitProblemReport(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitProblemReportMutationResult = NonNullable<Awaited<ReturnType<typeof submitProblemReport>>>
    export type SubmitProblemReportMutationBody = ProblemReportSubmitRequest
    export type SubmitProblemReportMutationError = ErrorResponse

    /**
 * @summary 문제 신고 제출
 */
export const useSubmitProblemReport = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitProblemReport>>, TError,{data: ProblemReportSubmitRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitProblemReport>>,
        TError,
        {data: ProblemReportSubmitRequest},
        TContext
      > => {
      return useMutation(getSubmitProblemReportMutationOptions(options), queryClient);
    }
