import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const assetDir = path.join(rootDir, 'apps/web/src/shared/assets/icons');
const outputFile = path.join(rootDir, 'apps/web/src/shared/ui/icon/icons.generated.ts');

/**
 * svg 파일명을 JavaScript 컴포넌트 이름으로 변환합니다.
 * @param {string} fileName
 * @returns {string}
 */
function toPascalCase(fileName) {
  return path
    .basename(fileName, '.svg')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('');
}

const files = (await readdir(assetDir, { withFileTypes: true }))
  .filter((entry) => entry.isFile() && path.extname(entry.name).toLowerCase() === '.svg')
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b, 'en'));

if (files.length === 0) {
  throw new Error(`No SVG files found in ${assetDir}`);
}

const icons = files.map((fileName) => ({
  componentName: toPascalCase(fileName),
  fileName,
  name: path.basename(fileName, '.svg'),
}));

const duplicateComponentNames = icons
  .map(({ componentName }) => componentName)
  .filter((name, index, names) => names.indexOf(name) !== index);

if (duplicateComponentNames.length > 0) {
  throw new Error(
    `SVG file names produce duplicate component names: ${[...new Set(duplicateComponentNames)].join(', ')}`
  );
}

const invalidComponent = icons.find(
  ({ componentName }) => !/^[A-Za-z_$][\w$]*$/.test(componentName)
);

if (invalidComponent) {
  throw new Error(
    `SVG file name cannot be converted to a component name: ${invalidComponent.fileName}`
  );
}

const imports = icons
  .map(
    ({ componentName, fileName }) =>
      `import ${componentName} from '@/shared/assets/icons/${fileName}?react';`
  )
  .join('\n');

const entries = icons
  .map(({ componentName, name }) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
    return `  ${key}: ${componentName},`;
  })
  .join('\n');

const content = `// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
${imports}

export const ICONS = {
${entries}
} as const;

export type IconName = keyof typeof ICONS;
`;

await writeFile(outputFile, content, 'utf8');

console.log(`Generated ${path.relative(rootDir, outputFile)} with ${icons.length} icons.`);
