/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  UnitPageResponse
} from '../model';

import { customInstance } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getAllUnitInChapterResponse200 = {
  data: UnitPageResponse
  status: 200
}

export type getAllUnitInChapterResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAllUnitInChapterResponseSuccess = (getAllUnitInChapterResponse200) & {
  headers: Headers;
};
export type getAllUnitInChapterResponseError = (getAllUnitInChapterResponse404) & {
  headers: Headers;
};

export type getAllUnitInChapterResponse = (getAllUnitInChapterResponseSuccess | getAllUnitInChapterResponseError)

export const getGetAllUnitInChapterUrl = (chapterId: number,) => {




  return `/api/v1/units/${chapterId}`
}

/**
 * 유저의 유닛 진행도를 포함한 유닛 목록을 조회합니다.<br>🔐 <strong>Jwt 필요</strong><br>
 * @summary 유닛 조회
 */
export const getAllUnitInChapter = async (chapterId: number, options?: RequestInit): Promise<getAllUnitInChapterResponse> => {

  return customInstance<getAllUnitInChapterResponse>(getGetAllUnitInChapterUrl(chapterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllUnitInChapterQueryKey = (chapterId: number,) => {
    return [
    `/api/v1/units/${chapterId}`
    ] as const;
    }


export const getGetAllUnitInChapterQueryOptions = <TData = Awaited<ReturnType<typeof getAllUnitInChapter>>, TError = ErrorResponse>(chapterId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUnitInChapterQueryKey(chapterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUnitInChapter>>> = ({ signal }) => getAllUnitInChapter(chapterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: chapterId !== null && chapterId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUnitInChapterQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUnitInChapter>>>
export type GetAllUnitInChapterQueryError = ErrorResponse


export function useGetAllUnitInChapter<TData = Awaited<ReturnType<typeof getAllUnitInChapter>>, TError = ErrorResponse>(
 chapterId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUnitInChapter>>,
          TError,
          Awaited<ReturnType<typeof getAllUnitInChapter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUnitInChapter<TData = Awaited<ReturnType<typeof getAllUnitInChapter>>, TError = ErrorResponse>(
 chapterId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUnitInChapter>>,
          TError,
          Awaited<ReturnType<typeof getAllUnitInChapter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUnitInChapter<TData = Awaited<ReturnType<typeof getAllUnitInChapter>>, TError = ErrorResponse>(
 chapterId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유닛 조회
 */

export function useGetAllUnitInChapter<TData = Awaited<ReturnType<typeof getAllUnitInChapter>>, TError = ErrorResponse>(
 chapterId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUnitInChapter>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUnitInChapterQueryOptions(chapterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






