/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 주관식 정답 Response
 */
export interface AnswerResponse {
    /**
     * 정답 내용
     */
    'content'?: string;
    /**
     * 정답 해설
     */
    'explanation'?: string;
}

