/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UnitSummary } from './unit-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLevelResponse } from './user-level-response';

/**
 * 풀이 결과 저장 Response
 */
export interface LearningSubmissionSaveResponse {
    /**
     * 리그 이름
     */
    'leagueName': string;
    /**
     * 유저 레벨 정보
     */
    'userLevelResponse': UserLevelResponse;
    /**
     * 유닛 요약 정보
     */
    'unitSummary': UnitSummary;
}

