/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 레슨 요약 정보
 */
export interface LessonSummary {
    /**
     * 레슨 아이디
     */
    'lessonId'?: number;
    /**
     * 레슨 제목
     */
    'title': string;
    /**
     * 전체 문제 수
     */
    'totalProblem'?: number;
    /**
     * 해결 여부
     */
    'isSolved'?: boolean;
}

