/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MissionDetail {
    /**
     * 미션 이름
     */
    'missionDescription'?: string;
    /**
     * 보상 xp
     */
    'awardXp'?: number;
    /**
     * 완료 여부
     */
    'isCompleted'?: boolean;
}

