/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface NoticeCreateRequest {
    'title'?: string;
    'content'?: string;
    'status'?: NoticeCreateRequestStatus;
    'pinned'?: boolean;
}

export const NoticeCreateRequestStatus = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED'
} as const;

export type NoticeCreateRequestStatus = typeof NoticeCreateRequestStatus[keyof typeof NoticeCreateRequestStatus];


