/* tslint:disable */
/* eslint-disable */
/**
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 옵션 수정 Request
 */
export interface OptionUpdateRequest {
    /**
     * 옵션 id
     */
    'optionId': number;
    /**
     * 내용
     */
    'content': string;
    /**
     * 설명
     */
    'explanation': string;
    /**
     * 정답 여부
     */
    'isAnswer': boolean;
}

