/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  LeagueRankRowDto,
  MyLeagueRankWithProfileResponse
} from '../model';


export const getGetLeagueRankingByUserResponseMock = (): LeagueRankRowDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({rank: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.helpers.arrayElement([faker.number.int(), undefined]), lp: faker.helpers.arrayElement([faker.number.int(), undefined]), nickname: faker.string.alpha({length: {min: 10, max: 20}}), profileImgNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), xp: faker.helpers.arrayElement([faker.number.int(), undefined]), level: faker.helpers.arrayElement([faker.number.int(), undefined])})))

export const getGetMyLeagueWithProfileResponseMock = (overrideResponse: Partial<Extract<MyLeagueRankWithProfileResponse, object>> = {}): MyLeagueRankWithProfileResponse => ({leagueId: faker.helpers.arrayElement([faker.number.int(), undefined]), leagueName: faker.string.alpha({length: {min: 10, max: 20}}), rank: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.helpers.arrayElement([faker.number.int(), undefined]), lp: faker.helpers.arrayElement([faker.number.int(), undefined]), maxLp: faker.helpers.arrayElement([faker.number.int(), undefined]), nickname: faker.string.alpha({length: {min: 10, max: 20}}), profileImgNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), xp: faker.helpers.arrayElement([faker.number.int(), undefined]), level: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getGetLeagueRankingResponseMock = (): LeagueRankRowDto[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({rank: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.helpers.arrayElement([faker.number.int(), undefined]), lp: faker.helpers.arrayElement([faker.number.int(), undefined]), nickname: faker.string.alpha({length: {min: 10, max: 20}}), profileImgNumber: faker.helpers.arrayElement([faker.number.int(), undefined]), xp: faker.helpers.arrayElement([faker.number.int(), undefined]), level: faker.helpers.arrayElement([faker.number.int(), undefined])})))


export const getGetLeagueRankingByUserMockHandler = (overrideResponse?: LeagueRankRowDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LeagueRankRowDto[]> | LeagueRankRowDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/ranking/user-leagues/page/:pageNum', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeagueRankingByUserResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetMyLeagueWithProfileMockHandler = (overrideResponse?: MyLeagueRankWithProfileResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MyLeagueRankWithProfileResponse> | MyLeagueRankWithProfileResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/ranking/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyLeagueWithProfileResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetLeagueRankingMockHandler = (overrideResponse?: LeagueRankRowDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LeagueRankRowDto[]> | LeagueRankRowDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/ranking/leagues/:leagueId/page/:pageNum', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeagueRankingResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserleagueApiMock = () => [
  getGetLeagueRankingByUserMockHandler(),
  getGetMyLeagueWithProfileMockHandler(),
  getGetLeagueRankingMockHandler()
]
