/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLessonsParams,
  PageResponseLessonListItemResponse,
  UnitDetailResponse,
  UnitUpdateRequest
} from '../model';

import { customInstance } from '../../mutator';




/**
 * @summary 유닛 상세 (lessonCount 포함)
 */
export const getUnit = (
    unitId: number,
 signal?: AbortSignal
) => {


      return customInstance<UnitDetailResponse>(
      {url: `/api/v1/admin/units/${unitId}`, method: 'GET', signal
    },
      );
    }




export const getGetUnitQueryKey = (unitId: number,) => {
    return [
    `/api/v1/admin/units/${unitId}`
    ] as const;
    }


export const getGetUnitQueryOptions = <TData = Awaited<ReturnType<typeof getUnit>>, TError = UnitDetailResponse>(unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnitQueryKey(unitId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnit>>> = ({ signal }) => getUnit(unitId, signal);





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUnitQueryResult = NonNullable<Awaited<ReturnType<typeof getUnit>>>
export type GetUnitQueryError = UnitDetailResponse


export function useGetUnit<TData = Awaited<ReturnType<typeof getUnit>>, TError = UnitDetailResponse>(
 unitId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnit>>,
          TError,
          Awaited<ReturnType<typeof getUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnit<TData = Awaited<ReturnType<typeof getUnit>>, TError = UnitDetailResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnit>>,
          TError,
          Awaited<ReturnType<typeof getUnit>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnit<TData = Awaited<ReturnType<typeof getUnit>>, TError = UnitDetailResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유닛 상세 (lessonCount 포함)
 */

export function useGetUnit<TData = Awaited<ReturnType<typeof getUnit>>, TError = UnitDetailResponse>(
 unitId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnit>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnitQueryOptions(unitId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 유닛 부분 수정
 */
export const updateUnit = (
    unitId: number,
    unitUpdateRequest: UnitUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/units/${unitId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: unitUpdateRequest, signal
    },
      );
    }



export const getUpdateUnitMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{unitId: number;data: UnitUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{unitId: number;data: UnitUpdateRequest}, TContext> => {

const mutationKey = ['updateUnit'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUnit>>, {unitId: number;data: UnitUpdateRequest}> = (props) => {
          const {unitId,data} = props ?? {};

          return  updateUnit(unitId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUnitMutationResult = NonNullable<Awaited<ReturnType<typeof updateUnit>>>
    export type UpdateUnitMutationBody = UnitUpdateRequest
    export type UpdateUnitMutationError = void

    /**
 * @summary 유닛 부분 수정
 */
export const useUpdateUnit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUnit>>, TError,{unitId: number;data: UnitUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUnit>>,
        TError,
        {unitId: number;data: UnitUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateUnitMutationOptions(options), queryClient);
    }
    /**
 * @summary 유닛의 레슨 목록
 */
export const getLessons = (
    unitId: number,
    params?: GetLessonsParams,
 signal?: AbortSignal
) => {


      return customInstance<PageResponseLessonListItemResponse>(
      {url: `/api/v1/admin/units/${unitId}/lessons`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLessonsQueryKey = (unitId: number,
    params?: GetLessonsParams,) => {
    return [
    `/api/v1/admin/units/${unitId}/lessons`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLessonsQueryOptions = <TData = Awaited<ReturnType<typeof getLessons>>, TError = unknown>(unitId: number,
    params?: GetLessonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLessonsQueryKey(unitId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLessons>>> = ({ signal }) => getLessons(unitId,params, signal);





   return  { queryKey, queryFn, enabled: unitId !== null && unitId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLessonsQueryResult = NonNullable<Awaited<ReturnType<typeof getLessons>>>
export type GetLessonsQueryError = unknown


export function useGetLessons<TData = Awaited<ReturnType<typeof getLessons>>, TError = unknown>(
 unitId: number,
    params: undefined |  GetLessonsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLessons>>,
          TError,
          Awaited<ReturnType<typeof getLessons>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLessons<TData = Awaited<ReturnType<typeof getLessons>>, TError = unknown>(
 unitId: number,
    params?: GetLessonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLessons>>,
          TError,
          Awaited<ReturnType<typeof getLessons>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLessons<TData = Awaited<ReturnType<typeof getLessons>>, TError = unknown>(
 unitId: number,
    params?: GetLessonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유닛의 레슨 목록
 */

export function useGetLessons<TData = Awaited<ReturnType<typeof getLessons>>, TError = unknown>(
 unitId: number,
    params?: GetLessonsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLessons>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLessonsQueryOptions(unitId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






