/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AuthorizeUrl200,
  LoginResponse
} from '../model';


export const getOauthLoginResponseMock = (overrideResponse: Partial<Extract<LoginResponse, object>> = {}): LoginResponse => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), isOnboarded: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getAuthorizeUrlResponseMock = (): AuthorizeUrl200 => ({
        [faker.string.alphanumeric(5)]: faker.string.alpha({length: {min: 10, max: 20}})
      })


export const getOauthLoginMockHandler = (overrideResponse?: LoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginResponse> | LoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/oauth/:provider', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getOauthLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAuthorizeUrlMockHandler = (overrideResponse?: AuthorizeUrl200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AuthorizeUrl200> | AuthorizeUrl200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/oauth/login-url/:provider', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthorizeUrlResponseMock(),
      { status: 200
      })
  }, options)
}
export const getOauth20ApiMock = () => [
  getOauthLoginMockHandler(),
  getAuthorizeUrlMockHandler()
]
