/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */

/**
 * 문의 답변 등록 request
 */
export interface InquiryAnswerCreateRequest {
  /**
     * 답변 내용
     * @minLength 1
     */
  content: string;
}
