/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */

export type SendInquiryAnsweredParams = {
/**
 * 헤드라인에 삽입될 문의 제목
 */
title?: string;
/**
 * 딥링크 대상 문의 ID
 */
inquiryId?: number;
};
