/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Gravit API Docs
 * 앱센터 16.5기 동계 프로젝트 Gravit API Docs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminInquiryDetailResponse,
  GetInquiriesParams,
  InquiryAnswerCreateRequest,
  InquiryAnswerUpdateRequest,
  PageResponseAdminInquiryListItemResponse
} from '../model';

import { customInstance } from '../../mutator';




/**
 * 등록된 답변 내용을 수정한다. 상태는 RESOLVED 로 유지된다.
 * @summary 문의 답변 수정
 */
export const updateAnswer = (
    inquiryId: number,
    inquiryAnswerUpdateRequest: InquiryAnswerUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<AdminInquiryDetailResponse>(
      {url: `/api/v1/admin/inquiries/${inquiryId}/answer`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: inquiryAnswerUpdateRequest, signal
    },
      );
    }



export const getUpdateAnswerMutationOptions = <TError = AdminInquiryDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{inquiryId: number;data: InquiryAnswerUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{inquiryId: number;data: InquiryAnswerUpdateRequest}, TContext> => {

const mutationKey = ['updateAnswer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAnswer>>, {inquiryId: number;data: InquiryAnswerUpdateRequest}> = (props) => {
          const {inquiryId,data} = props ?? {};

          return  updateAnswer(inquiryId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof updateAnswer>>>
    export type UpdateAnswerMutationBody = InquiryAnswerUpdateRequest
    export type UpdateAnswerMutationError = AdminInquiryDetailResponse

    /**
 * @summary 문의 답변 수정
 */
export const useUpdateAnswer = <TError = AdminInquiryDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnswer>>, TError,{inquiryId: number;data: InquiryAnswerUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAnswer>>,
        TError,
        {inquiryId: number;data: InquiryAnswerUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateAnswerMutationOptions(options), queryClient);
    }
    /**
 * 답변 등록 시 문의 상태가 RESOLVED 로 자동 전환되고 작성자에게 알림이 발송된다.
 * @summary 문의 답변 등록
 */
export const answerInquiry = (
    inquiryId: number,
    inquiryAnswerCreateRequest: InquiryAnswerCreateRequest,
 signal?: AbortSignal
) => {


      return customInstance<AdminInquiryDetailResponse>(
      {url: `/api/v1/admin/inquiries/${inquiryId}/answer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inquiryAnswerCreateRequest, signal
    },
      );
    }



export const getAnswerInquiryMutationOptions = <TError = AdminInquiryDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof answerInquiry>>, TError,{inquiryId: number;data: InquiryAnswerCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof answerInquiry>>, TError,{inquiryId: number;data: InquiryAnswerCreateRequest}, TContext> => {

const mutationKey = ['answerInquiry'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof answerInquiry>>, {inquiryId: number;data: InquiryAnswerCreateRequest}> = (props) => {
          const {inquiryId,data} = props ?? {};

          return  answerInquiry(inquiryId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AnswerInquiryMutationResult = NonNullable<Awaited<ReturnType<typeof answerInquiry>>>
    export type AnswerInquiryMutationBody = InquiryAnswerCreateRequest
    export type AnswerInquiryMutationError = AdminInquiryDetailResponse

    /**
 * @summary 문의 답변 등록
 */
export const useAnswerInquiry = <TError = AdminInquiryDetailResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof answerInquiry>>, TError,{inquiryId: number;data: InquiryAnswerCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof answerInquiry>>,
        TError,
        {inquiryId: number;data: InquiryAnswerCreateRequest},
        TContext
      > => {
      return useMutation(getAnswerInquiryMutationOptions(options), queryClient);
    }
    /**
 * 답변 삭제 시 문의 상태가 PENDING 으로 되돌아간다.
 * @summary 문의 답변 삭제
 */
export const deleteAnswer = (
    inquiryId: number,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/v1/admin/inquiries/${inquiryId}/answer`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteAnswerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAnswer>>, TError,{inquiryId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAnswer>>, TError,{inquiryId: number}, TContext> => {

const mutationKey = ['deleteAnswer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAnswer>>, {inquiryId: number}> = (props) => {
          const {inquiryId} = props ?? {};

          return  deleteAnswer(inquiryId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAnswer>>>

    export type DeleteAnswerMutationError = void

    /**
 * @summary 문의 답변 삭제
 */
export const useDeleteAnswer = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAnswer>>, TError,{inquiryId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAnswer>>,
        TError,
        {inquiryId: number},
        TContext
      > => {
      return useMutation(getDeleteAnswerMutationOptions(options), queryClient);
    }
    /**
 * status 미지정 시 전체 조회. 1-based 페이지, id 내림차순.
 * @summary 문의 목록(상태별)
 */
export const getInquiries = (
    params?: GetInquiriesParams,
 signal?: AbortSignal
) => {


      return customInstance<PageResponseAdminInquiryListItemResponse>(
      {url: `/api/v1/admin/inquiries`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetInquiriesQueryKey = (params?: GetInquiriesParams,) => {
    return [
    `/api/v1/admin/inquiries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetInquiriesQueryOptions = <TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(params?: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInquiriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInquiries>>> = ({ signal }) => getInquiries(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInquiriesQueryResult = NonNullable<Awaited<ReturnType<typeof getInquiries>>>
export type GetInquiriesQueryError = unknown


export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params: undefined |  GetInquiriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiries>>,
          TError,
          Awaited<ReturnType<typeof getInquiries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params?: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiries>>,
          TError,
          Awaited<ReturnType<typeof getInquiries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params?: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 문의 목록(상태별)
 */

export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params?: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInquiriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 작성자 정보와 답변(있으면)을 포함한다.
 * @summary 문의 상세
 */
export const getInquiry = (
    inquiryId: number,
 signal?: AbortSignal
) => {


      return customInstance<AdminInquiryDetailResponse>(
      {url: `/api/v1/admin/inquiries/${inquiryId}`, method: 'GET', signal
    },
      );
    }




export const getGetInquiryQueryKey = (inquiryId: number,) => {
    return [
    `/api/v1/admin/inquiries/${inquiryId}`
    ] as const;
    }


export const getGetInquiryQueryOptions = <TData = Awaited<ReturnType<typeof getInquiry>>, TError = AdminInquiryDetailResponse>(inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInquiryQueryKey(inquiryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInquiry>>> = ({ signal }) => getInquiry(inquiryId, signal);





   return  { queryKey, queryFn, enabled: inquiryId !== null && inquiryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInquiryQueryResult = NonNullable<Awaited<ReturnType<typeof getInquiry>>>
export type GetInquiryQueryError = AdminInquiryDetailResponse


export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = AdminInquiryDetailResponse>(
 inquiryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiry>>,
          TError,
          Awaited<ReturnType<typeof getInquiry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = AdminInquiryDetailResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiry>>,
          TError,
          Awaited<ReturnType<typeof getInquiry>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = AdminInquiryDetailResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 문의 상세
 */

export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = AdminInquiryDetailResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInquiryQueryOptions(inquiryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






